<div class="balance">

	<h1>Egyenleg</h1>

	<div class="now">
		<? $avail=Zend_Registry::get('uploadPrice')==0 ? 'végtelen' : floor($this->user->balance/Zend_Registry::get('uploadPrice'));?>
		<strong>Jelenlegi egyenleged: <?=$this->user->balance;?> Ft. </strong><br />
		Ne feledd, 10 aktív termék erejéig a feltöltés ingyenes!<br />
		<?=($avail>0 || Zend_Registry::get('uploadPrice')==0) ? 'Ez még '.$avail.' termék feltöltésére elegendő' : 'További termékek feltöltéséhez, egyéb szolgáltatásokhoz töltsd fel egyenleged!!';?>
	</div>

	<h2>Egyenleg feltöltése</h2>
	<? if(!$this->user->isValid()){?>
		<h3>Egyenleg feltöltéséhez minden szükséges adatot meg kell adnod az <a href="<?=$this->url('adatmodositas');?>">adatmódosítás</a> oldalon</h3>
	<? } else {?>
		<div class="card stat">
			<h3 class="cardBarionTitle">Fizetés bankkártyával vagy <img src="/img/elements/barion_icon.png" alt="Barion"/> - nal</h3>
			<p>Írd be az összeget (min. <?=Zend_Registry::get('minCharge');?> Ft.), kattints a "Fizetés bankkártyával" gombra és fizess bankkártyáddal azonnal.</p>
			<?=$this->form;?>
			<p class="chargeAvail">Az összeg <span>0</span> termék feltöltésére elegendő</p>
			<p class="barionInfo">
				A kényelmes és biztonságos online fizetést a Barion Payment Zrt. biztosítja. Magyar Nemzeti Bank engedély száma: H-EN-I-1064/2013 <br/>
				Bankkártya adatai áruházunkhoz nem jutnak el. <br />
				<img src="/img/elements/barion_norton.png" alt="Norton secured"/>
			</p>
		</div>

		<div class="transfer stat">
			<h3>Fizetés átutalással</h3>
            <br />
			<p>Töltsd fel egyenleged minimum <?=Zend_Registry::get('minCharge');?> Ft-al az alábbi számlaszámra való utalással:</p>
			<p>
				<strong>Számlaszám:</strong> 10401804-50515548-53541005 <br />
				<strong>Bank:</strong> K&H Bank <br />
				<strong>Kedvezményezett neve:</strong> Csakbaba.hu Kft. <br />
				<strong>Közlemény:</strong> <?=strtoupper(substr($this->user->username, 0, 4).substr(md5($this->user->id), 0, 4));?>
			</p>
		</div>
	<? } ?>



</div>

<div class="stat">

	<h1>Számláim</h1>

	<div class="payments">
		<table>
			<tr>
				<th>Dátum</th>
				<th>Összeg</th>
				<th>Fizetés módja</th>
				<th>Azonosító</th>
				<th>Számla</th>
			</tr>
		<? foreach($this->payments as $payment){?>
			<? if($payment->status==1) continue;?>
			<tr>
				<td><?=$payment->date->format('Y.m.d H:i:s');?></td>
				<td><?=$payment->amount;?> Ft.</td>
				<td><?
					switch($payment->type){
						case 'CREDIT_CARD':  echo 'Bankkártya';break;
						case 'BANK_TRANSFER':  echo 'Átutalás';break;
						default: echo '';break;
					};?></td>
				<td><?=$payment->pid;?></td>
				<td><a href="<?=$this->url('egyenleg').'?i=1&pid='.$payment->pid;?>" target="_blank"><?=$payment->invoice_data['invoice_number'];?></a></td>
			</tr>
		<? } ?>
		</table>
	</div>

</div>

