<div class="userEditForm">
	<? if(!empty($_GET['nyitas'])){ ?>
		<div class="stat nyitas">
			<p><strong>Asztal nyitásához az alábbi adatok közül mindent meg kell adnod (Alapadatok, számlázási - és postázási cím)!</strong></p>
			<!--<p>Egyenleged feltöltheted átutalással, banki befizetessel, ehhez a részleteket <a href="<?=$this->url('egyenleg');?>">ITT</a> találod, vagy feltöltheted azonnal, bankkártyával <a href="<?=$this->url('egyenleg');?>">ITT</a>! Ne felejts el, hogy egyenleged min. 320Ft-tal kell feltöltened, ami kiemelesek nélkül 8 termék feltöltesere elegendő. Jó börzézést kívánunk!!!</p>-->
			<p>A vásárlás, eladás részleteiről <a href="<?=$this->url('rolunk');?>">ide kattintva</a> olvashatsz.</p>
		</div>
	<? } ?>
	<?=$this->form;?>
</div>
