<h1 class="pageName"> Kedvencek </h1>
<div class="favourites">
	<div class="productList">
		<ul class="products">

			<? foreach($this->favourites as $product){?>
				<?=$this->partial('market/product-partial.phtml', array_merge($this->getVars(), array('product'=>$product, 'delFav'=>true)));?>
			<? } ?>

            <? if(empty($this->favourties)){?>
                <div class="noFavs">
                    <p class="infoText">Még nincsenek kedvenceid</p>
                    <a class="favouritesMarket" href="<?=$this->url('piac');?>">Irány a börze</a>
                </div>
                
            <? } ?>

		</ul>
	</div>
</div>