<h2>Bejelentkezés</h2>
<div class="loginForm">
	<div class="socialLogin">
		<a href="/slogin?s=fb" class="fb" title="Bejelentkezés Facebook fiókkal">Bejelentkezés Facebook fiókkal</a>
		<a href="/slogin?s=gp" class="gp" title="Bejelentkezés Google fiókkal">Bejelentkezés Google fiókkal</a>
	</div>

    <p class="regLoginOr">vagy</p>

    <?=$this->form;?>
	<div class="regForgotten">
        <a href="/regisztracio" class="regLink">Regisztráció</a>
        <a href="<?=$this->url('elfelejtett');?>" class="forgotten">Elfelejtett jelszó</a>
	</div>

</div>

