<div class="orders">
	<div class="orderFilter">
		<a href="javascript:void(0);" class="tab" data-div="nem-ertekelt">Nem értékelt</a>
		<a href="javascript:void(0);" class="tab" data-div="vasarolt">Vásárolt</a>
		<a href="javascript:void(0);" class="tab" data-div="eladott">Eladott</a>
	</div>


	<div class="productList user">

		<ul>

			<? foreach($this->userOrdersBuy as $o){?>
				<? if($o->user_rating) $o->user_rating->get();?>
				<? if($o->shop_user_rating) $o->shop_user_rating->get();?>

				<?=$this->partial('market/product-partial.phtml', array_merge($this->getVars(),
								array('product'=>$o->product, 'categoryTree'=>$this->categoryTree, 'back'=>false, 'fix'=>false, 'userfunctions'=>false, 'o'=>$o, 'rating'=>true,
												'extraClass'=>'order vasarolt '.($o->user_rating ? '' : 'nem-ertekelt').' pid'.$o->product->get()->id, 'extraData'=>'data-orderid="'.$o->id.'" data-productid="'.$o->product->get()->id.'" data-seller="0"', 'seller'=>false, 'showBoth'=>true)));?>
			<? } ?>


			<? foreach($this->userOrdersSell as $o){?>
				<? if($o->user_rating) $o->user_rating->get();?>
				<? if($o->shop_user_rating) $o->shop_user_rating->get();?>
				<?=$this->partial('market/product-partial.phtml', array_merge($this->getVars(),
								array('product'=>$o->product, 'categoryTree'=>$this->categoryTree, 'back'=>false, 'fix'=>false, 'userfunctions'=>false, 'o'=>$o, 'rating'=>true,
												'extraClass'=>'order eladott '.($o->shop_user_rating ? '' : 'nem-ertekelt').' pid'.$o->product->get()->id, 'extraData'=>'data-orderid="'.$o->id.'" data-productid="'.$o->product->get()->id.'" data-seller="1"', 'seller'=>true, 'showBoth'=>true)));?>
			<? } ?>

		</ul>

	</div>
</div>