

<div class="profile">
	<div class="profilMenu">
	<? if(($this->user) && $this->user->id==$this->profilUser->id){?>
		<? $pages=Zend_Registry::get('nav')->findBy('resource', 'felhasznalo')->getPages(); ?>
			<ul>
				<? foreach($pages as $page){?>
						<? if($page->get('profileVisible') === false) continue; ?>
					<li><a href="<?=$page->getUri();?>"><span><?=$page->getLabel();?></span></a></li>
				<? } ?>
			</ul>
	<? } ?>
	</div>


	<div class="userData">

		<div class="avatarInfo">
			<div class="avatar">
				<? $img=(is_array($this->profilUser->avatar) && !empty($this->profilUser->avatar)) ? $img=reset($this->profilUser->avatar) : array('url'=>'/img/elements/defaultproduct.png'); ?>
				<img src="<?=$img['url'];?>" alt="<?=$this->profilUser->username;?>"/>
			</div>
			<div class="info">
				<p class="username"><?=$this->profilUser->username;?></p>
				<p class="city"><strong>Város:</strong> <?=(!empty($this->profilUser->postaddress['city']) ? $this->profilUser->postaddress['city'] : '');?></p>
				<p class="regdate"><strong>Regisztrált:</strong> <?=$this->profilUser->date_reg->format('Y. m. d.');?></p>
				<div class="rating">
					<strong>Értékelés:</strong>&nbsp;
					<span><?=($rating=$this->profilUser->getRating())*5;?></span>
					<div class="ratingContainer"><div class="ratingInner" style="width: <?=($rating*100);?>%;"></div></div>
				</div>
			</div>
		</div>

		<div class="desc stat">
			<?=$this->profilUser->desc;?>
		</div>
	</div>
	<div class="marketProducts">
        <div class="profileFilter">
            <a href="javascript:void(0);" class="tab" data-div="status1">Aktív termékek</a>
            <a href="javascript:void(0);" class="tab" data-div="status2">Eladott termékek</a>
        </div>


		<div class="productList">
			<ul class="products">

				<? foreach($this->userProducts as $product){?>
					<?=$this->partial('market/product-partial.phtml', array_merge($this->getVars(), array('product'=>$product, 'back'=>false, 'fix'=>false)));?>
				<? } ?>

			</ul>
		</div>
	</div>
</div>