<div class="userrenew" data-productid="<?=$this->product->id;?>">
	<div class="balance">
		<p><strong>A feltöltés díja <?=Zend_Registry::get('uploadPrice');?> Ft.</strong></p>
		<br />
		<p><strong>Aktuális gyenleged</strong>: <span><?=$this->user->balance;?></span> Ft</p>
	</div>
	<? if($this->user->balance < Zend_Registry::get('uploadPrice')){?>
		<p class="noBalance">Nincs elég pénz az egyenlegeden a megújításhoz. <a href="<?=$this->url('egyenleg');?>">Töltsd fel az egyenleged.</a></p>
	<? } else { ?>
		<a href="javascript:void(0);" class="renewButton">Feltöltöm újra</a>
	<? } ?>

</div>

