<div class="rating">
	<?
		$firstProp=($this->seller ? 'shop_user_rating' : 'user_rating');
		$secondProp=($this->seller ? 'user_rating' : 'shop_user_rating');
		$username=($this->seller ? $this->o->user->username : $this->o->shop_user->username);
	?>
	<? $hideOwn=isset($this->hideOwn) && $this->hideOwn;?>
	<? $showBoth=isset($this->showBoth) && $this->showBoth;?>

	<? if($showBoth || (!$this->seller && $hideOwn)){?>
		<? if($this->o->$firstProp){?>
			<div class="userRating">
				<h4>Te értékelésed</h4>
				<p class="date"><strong>Értékelés dátuma:</strong> <?=$this->o->$firstProp->date->format('Y-m-d H:i');?></p>
				<p class="succes"><strong>Sikeres rendelés:</strong> <?=$this->o->$firstProp->success ? 'igen' : 'nem';?></p>
				<p class="positive"><strong>Értékelés:</strong> <?=$this->o->$firstProp->positive ? 'Pozitív' : 'Negatív';?></p>
				<p class="text"><strong>Szöveges értékelés:</strong> <?=$this->o->$firstProp->text;?></p>
			</div>
		<? } ?>
	<? } ?>

	<? if($showBoth || ($this->seller && $hideOwn)){?>
		<? if($this->o->$secondProp){?>
			<div class="shopUserRating">
				<h4><?=$username;?> értékelése</h4>
				<p class="date"><strong>Értékelés dátuma:</strong> <?=$this->o->$secondProp->date->format('Y-m-d H:i');?></p>
				<p class="succes"><strong>Sikeres rendelés:</strong> <?=$this->o->$secondProp->success ? 'igen' : 'nem';?></p>
				<p class="positive"><strong>Értékelés:</strong> <?=$this->o->$secondProp->positive ? 'Pozitív' : 'Negatív';?></p>
				<p class="text"><strong>Szöveges értékelés:</strong> <?=$this->o->$secondProp->text;?></p>
			</div>
		<? } ?>
	<? } ?>

</div>