<div class="productEditAddForm service" data-balance="<?=$this->user->balance ?: 0;?>"
     data-productid="<?=($this->service ? $this->service_id : '');?>"
     data-categoryid="<?=($this->category ? $this->category->id : '');?>"
>

    <div class="formActions">
        <a href="javascript:void(0)" class="productEditPopupButton save">Mentés</a>
    </div>
    
    <div class="form">
        
    </div>



</div>

