
<?php if(isset($this->categoryOptions)) {?>
<form method="get" class="filter">
	<!--<div class="filterSubmit"><a href="javascript:void(0)" class="filterSubmitLink">Szűrés</a></div>-->

	<div class="categoryOptions">
		<input type="hidden" value="<?=$this->category->id;?>" name="category_id"/>
		<?php $props=Zend_Registry::get('categories')->_props; ?>
		<?php foreach($this->categoryOptions as $oid=>$option){ ?>
			<?php $id=$option; $option=$props[$option]; ?>
			<div class="optionWrapper">
				<div class="option">
					<a href="javascript:void(0)" class="<?=(in_array($option['slug'], $_GET)) ? 'set' : '';?>"><?=$option['name'];?></a>
					<?php if($option['type']=='select'){?>
						<ul>
							<?php foreach($option['options'] as $o){?>
								<li class="checkbox">
									<input type="checkbox" name="<?=$option['slug'];?>[]" value="<?=$o['value'];?>" id="<?=$id.$o['value'];?>" <?php if(!empty($_GET[$option['slug']]) && in_array($o['value'], $_GET[$option['slug']])) echo 'checked="checked"'; ?>/>
									<label for="<?=$id.$o['value'];?>"><?=$o['name'];?></label>
								</li>
							<?php } ?>
						</ul>
					<?php } ?>
					<?php if($option['type']=='number'){?>
						<?php $value=!empty($_GET[$option['slug']]) ? $_GET[$option['slug']] : $option['min'].'-'.$option['max'];?>
						<ul>
							<li><input class="range" type="text" name="<?=$option['slug'];?>" id="<?=$id;?>" data-min="<?=$option['min'];?>" data-range="true" data-step="<?=isset($option['step']) ? $option['step'] : 1;?>" data-max="<?=$option['max'];?>" value="<?=$value;?>" /></li>
						</ul>
					<?php } ?>

				</div>
			</div>
		<?php } ?>

		<?php if($this->category->sex==true){?>
			<div class="optionWrapper">
				<div class="option">
					<a href="javascript:void(0)">Nem</a>
					<ul>
						<?php foreach(Zend_Registry::get('genreTypes') as $slug=>$type){?>
							<li class="checkbox">
								<input type="checkbox" name="<?=$slug;?>" value="1" id="<?=$slug;?>" <?php if(array_key_exists($slug, $_GET)) echo 'checked="checked"'; ?>/>
								<label for="<?=$slug;?>"><?=$type;?></label>
							</li>
						<?php } ?>
					</ul>

				</div>
			</div>
		<?php } ?>


		<div class="optionWrapper">
			<div class="option">
				<a href="javascript:void(0)">Rendezés</a>
				<ul>
					<li class="radio">
						<div class="radios">
							<label>
								<input type="radio" name="sort" value="search_name-asc"/>
								abc &#8593;
							</label>
							<label>
								<input type="radio" name="sort" value="search_name-desc"/>
								abc &#8595;
							</label>
							<label>
								<input type="radio" name="sort" value="date_added-asc"/>
								Dátum &#8593;
							</label>
							<label>
								<input type="radio" name="sort" value="date_added-desc"/>
								Dátum &#8595;
							</label>
							<label>
								<input type="radio" name="sort" value="price-asc"/>
								Ár &#8593;
							</label>
							<label>
								<input type="radio" name="sort" value="price-desc"/>
								Ár &#8595;
							</label>
						</div>
					</li>
				</ul>

			</div>
		</div>

		<div class="submit">
			<input type="submit" value="Szűrés" />
		</div>
	</div>
</form>
<?php } ?>

