<h2>Keresési találatok erre: <em><?=$this->q;?></em></h2>

<script type="text/javascript">
	ga('send', 'event', 'search', 'results', '<?=$this->q;?>');
</script>

<? if(empty($this->results)){?>
	<p class="noResults">Nincs találat</p>
<? } ?>

<div class="productList">

	<ul class="products">

		<? foreach($this->results as $result){?>
			<? $product=$result['product'];?>
			<?=$this->partial('market/product-partial.phtml', array_merge($this->getVars(), array('product'=>$product)));?>
		<? } ?>

	</ul>
    
    <div class="buttonBack"><a href="<?=$this->url('piac');?>">Vissza a börzére </a></div>
</div>

<script type="text/javascript">
    $(window).load(function(){
    	setTimeout(function(){
		    $('html, body').scrollTop(0);
        }, 500);
    });
</script>