<div class="cassaThanks">
    <div class="thx">
			<h2>Gratulálunk, sikeresen megvásároltad a terméket! <br /> Az eladónak és Neked emailben elküldtük az általatok megadott elérhetőségeiteket, amely alapján felvehetitek egymással a kapcsolatot! Az adás-vétel után ne felejtsd el értékelni a tranzakciót!</h2>
			<p>Köszönjük a vásárlást!</p>
			<p>A csakbaba.hu csapata</p>
    </div>
    <div class="buttons">
        <a href="<?=$this->url('felhasznalotermekek');?>?uj" class="upload">Tölts fel te is terméket.</a>
        <a href="<?=$this->url('piac');?>" class="continueShopping">Folytasd a vásárlást!</a>
    </div>
	<div class="promoter">
		<?=$this->partial('index/promote_partial.phtml', array('products'=>$this->promoted, 'type'=>'first', 'categoryTree'=>$this->categoryTree, 'request'=>$this->request));?>
	</div>

</div>

