<p>Kedves <strong><?=$this->data['user']->username;?></strong>!<br /></p>
<br />
<p>Üdvözlünk a csakbaba<span>.hu</span>  oldalon!</p>
<p>A mai napon az alábbi adatokkal regisztráltál oldalunkon:</p>
<ul>
	<li>Felhasználó név: <strong><?=$this->data['user']->username;?></strong></li>
	<li>E-mail: <strong><a href="mailto:<?=$this->data['user']->email;?>"><?=$this->data['user']->email;?></a></strong></li>
</ul>
<br />
<p><strong>Aktiváld regisztrációdat az alábbi linkre kattintva: </strong><br />
<a href="<?=$this->data['activation_link'];?>"><?=$this->data['activation_link'];?></a>
</p>
<br />
<p>Ne felejtsd, hogy regisztrálásoddal elfogadtad az oldal Általános szerződési feltételeit, kérjük, hogy a benne foglaltakat vedd figyelembe, amikor vásárolsz/eladsz a csakbaba<span>.hu</span> oldalon!</p>

Köszönjük, hogy igénybe vetted a csakbaba<span>.hu</span> szolgáltatásait!
<br />
<p>Üdvözlettel,<br />
a csakbaba<span>.hu</span> csapata <br />
<a href="<?='https://'.$_SERVER['HTTP_HOST'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?></a></p>



