<p>Kedves <strong><?=$this->data['user']->username;?></strong>!<br /></p>
<br />
<p>Szeretnénk emlékeztetni, hogy korábban regisztráltál a <a href="<?='https://'.$_SERVER['HTTP_HOST'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?></a> online bababörzén, de eddig nem aktiváltad felhasználói profilodat.</p>
<br />
<p><strong>Amennyiben szeretnéd, ezt most megteheted az alábbi linkre kattintva: </strong><br />
<a href="<?=$this->data['activation_link'];?>"><?=$this->data['activation_link'];?></a>
</p>
<br />
<p>Ha időközben esetleg meggondoltad magad, akkor tekintsd levelünket tárgytalannak!</p>
<br />
<p>Üdvözlettel,<br />
a csakbaba<span>.hu</span> csapata <br />
<a href="<?='https://'.$_SERVER['HTTP_HOST'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?></a></p>



