<p>Kedves tagunk!</p>
<br />
<p>Amennyiben még nem tetted, kérjük lépj be oldalunkra, ismerd meg és ha egyetértesz vele fogadd el Adatkezelési gyakorlatunkról szóló tájékoztatónkat.</p>
<br />
<p><a href="https://csakbaba.hu/adatvedelem">https://csakbaba.hu/adatvedelem</a></p>
<br />
<p>Amennyiben nem kívánsz tovább tagunk lenni lehetőséged van az Adatkezelési tájékoztatóban foglaltak szerint törölni a profilodat, a hirdetéseidet és a rendszeren belül folytatott levelezésedet is.</p>
<br />
<br />
<p>Üdvözlettel,<br />
   a csakbaba<span>.hu</span> csapata <br />
	<a href="<?='https://'.$_SERVER['HTTP_HOST'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?></a></p>