<p>Kedves <strong><?=$this->data['user']->username;?></strong>!<br /></p>
<br />
<p>Értesítünk, hogy a csakbaba<span>.hu</span> felhasználói egyenleged hamarosan feltöltésre szorul. Egyenleged banki befizetéssel, ill. bankszámlára történő befizetéssel egyenlítheted ki. Az egyenleged tetszőleges összeggel feltöltheted, de a minimálisan feltöltendő összeg <?=Zend_Registry::get('minCharge');?> Ft. </p>
<br />
<p>Egyenleged az alábbi számlára utalással/banki befizetéssel töltheted fel: <br />
A számlatulajdonos/kedvezményezett neve: Csakbaba.hu Kft. <br />
Bankszámlaszám: K&H Bank 10401804-50515548-53541005 </p>
<br />
<p>Megjegyzés rovatban tüntesd fel ezt a kódot: <?=strtoupper(substr($this->data['user']->username, 0, 4).substr(md5($this->data['user']->id), 0, 4));?>!</p>

<p>Számlád részleteit a mellékletben csatolt számla letöltésekor ill. a bolt/felhasználói oldaladon a „pénzügyi adataim” menüpontban a „számláim” menüben tekintheted meg. Számládat pdf formátumban küldjük, amelyet az ingyenesen letölthető acrobat reader program segítségével tudsz megnyitni.
	<br />
A befizetésről szóló szabályzatunkról, és díjtételeinkről az alábbi menüpontra kattintva tájékozódhatsz: <a href="<?='https://'.$_SERVER['HTTP_HOST'];?>/<?=$this->url('rolunk');?>">Mi az a csakbaba?</a>
	<br />
Kérjük, hogy egyenleged folyamatosan kísérd figyelemmel, mert az időben feltöltött egyenleg feltétele a zavartalan termékfeltöltésnek.
	<br />
Ha van elmaradt értékelésed, kérjük azt is pótold! </p>
<br />
Köszönjük az együttműködésedet és, hogy igénybe vetted a csakbaba<span>.hu</span> szolgáltatásait!
<br />
<p>Üdvözlettel,<br />
a csakbaba<span>.hu</span> csapata <br />
<a href="<?='https://'.$_SERVER['HTTP_HOST'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?></a></p>
