<p>Kedves blog szerkesztő!<br /></p>
<br />
<p>A csakbaba<span>.hu</span> oldalon új hozzászólás érkezett a <strong><a href="<?='https://'.$_SERVER['HTTP_HOST'];?><?=$this->url('blog');?>/<?=$this->data['post']->slug;?>"><?=$this->data['post']->title;?></a></strong> blog cikkhez</p>
<br />
<p>Üdvözlettel,<br />
a csakbaba<span>.hu</span> csapata <br />
<a href="<?='https://'.$_SERVER['HTTP_HOST'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?></a></p>

