<p>Kedves <strong><?=$this->data['shop_user']->username;?></strong>!<br /></p>
<br />
<p>Gratulálunk, a mai napon eladtad az alábbi terméked a csakbaba<span>.hu</span> oldalon:</p>
<ul>
	<li>Termék neve: <strong><?=$this->data['product']->name;?></strong></li>
	<li>Termék kódja: <strong><?=$this->data['product']->code;?></strong></li>
	<li>Termék ára: <strong><?=$this->data['product']->price;?> Ft.</strong></li>
	<li>Termék linkje: <br /><a href="<?='https://'.$_SERVER['HTTP_HOST'];?><?=$this->url('piac');?><?=$this->data['productlink'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?><?=$this->url('piac');?><?=$this->data['productlink'];?></a></li>
</ul>

<p><strong>A vásárló adatai:</strong></p>
<ul>
	<li>Felhasználó neve: <strong><a href="<?='https://'.$_SERVER['HTTP_HOST'];?><?=$this->url('profil').'/'.$this->data['user']->username;?>"><?=$this->data['user']->username;?></a></strong></li>
	<li>Név: <strong><?=$this->data['user']->postaddress['name'];?></strong></li>
	<li>E-mail: <strong><a href="mailto:<?=$this->data['user']->email;?>"><?=$this->data['user']->email;?></a></strong></li>
	<li>Telefonszáma: <strong><?=str_replace('-', '<span>-</span>', $this->data['user']->phone);?></strong></li>
	<li>Szállítási címe: <strong><?=$this->data['user']->postaddress['zip'];?> <?=$this->data['user']->postaddress['city'];?> <?=$this->data['user']->postaddress['street'];?></strong></li>
	<li>Tranzakció kódja: <strong><?=$this->data['order']->code;?></strong></li>
</ul>

<p>A gyors lebonyolítás érdekében, minél előbb vedd fel a kapcsolatot az eladóval. A tranzakció lebonyolítására 14 nap áll a rendelkezésedre. <br />
Kérjük, ne felejtsd el értékelni az adás-vételt! <br />
Ezt az <a href="<?='https://'.$_SERVER['HTTP_HOST'];?><?=$this->url('ertekelesek');?>">alábbi linken keresztül</a> ill. a csakbaba<span>.hu</span> felhasználói oldaladon a "Vásárolt termékeim" menüpontban megteheted!</p>

<p>Köszönjük, hogy igénybe vetted a csakbaba<span>.hu</span> szolgáltatásait!</p>

<br />
<p>
Üdvözlettel,<br />
a csakbaba<span>.hu</span> csapata <br />
<a href="<?='https://'.$_SERVER['HTTP_HOST'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?></a>
</p>
