<p>Kedves <strong><?=$this->data['user']->username;?></strong>!<br /></p>
<br />
<p>A csakbaba<span>.hu</span> oldalon az alábbi terméket vásároltad meg:</p>
<ul>
	<li>Termék neve: <strong><?=$this->data['product']->name;?></strong></li>
	<li>Termék kódja: <strong><?=$this->data['product']->code;?></strong></li>
	<li>Termék ára: <strong><?=$this->data['product']->price;?> Ft.</strong></li>
	<li>Termék linkje: <br /><a href="<?='http://'.$_SERVER['HTTP_HOST'];?><?=$this->url('piac');?><?=$this->data['productlink'];?>"><?='http://'.$_SERVER['HTTP_HOST'];?><?=$this->url('piac');?><?=$this->data['productlink'];?></a></li>
</ul>

<p><strong>Az eladó adatai:</strong></p>
<ul>
	<li>Felhasználó neve: <strong><a href="<?='http://'.$_SERVER['HTTP_HOST'];?><?=$this->url('profil').'/'.$this->data['shop_user']->username;?>"><?=$this->data['shop_user']->username;?></a></strong></li>
	<li>Név: <strong><?=$this->data['shop_user']->address['name'];?></strong></li>
	<li>E-mail: <strong><a href="mailto:<?=$this->data['shop_user']->email;?>"><?=$this->data['shop_user']->email;?></a></strong></li>
	<li>Telefonszáma: <?=str_replace('-', '<span>-</span>', $this->data['shop_user']->phone);?></li>
	<li>Tranzakció kódja: <?=$this->data['order']->code;?></li>
</ul>

<p>A gyors lebonyolítás érdekében, minél előbb vedd fel a kapcsolatot az eladóval. A tranzakció lebonyolítására 14 nap áll a rendelkezésedre. <br />
Kérjük, ne felejtsd el értékelni az adás-vételt, mert az időben adott értékelés mindannyiunk érdeke! <br />
Ezt az <a href="<?='http://'.$_SERVER['HTTP_HOST'];?><?=$this->url('ertekelesek');?>">alábbi linken keresztül</a> ill. a csakbaba<span>.hu</span> felhasználói oldaladon a "Vásárolt termékeim" menüpontban megteheted!</p>

<p>Köszönjük, hogy igénybe vetted a csakbaba<span>.hu</span> szolgáltatásait!</p>

<br />
<p>
Üdvözlettel,<br />
a csakbaba<span>.hu</span> csapata <br />
<a href="<?='http://'.$_SERVER['HTTP_HOST'];?>"><?='http://'.$_SERVER['HTTP_HOST'];?></a>
</p>
