<p>Kedves <strong><?=$this->data['user']->username;?></strong>!<br /></p>
<br />
<p>Egyenleged feltöltése sikeres volt!</p>
<p><strong>Feltöltött összeg:</strong> <?=$this->data['payment']->amount;?> Ft.</p>
<br />
<p>Erről a mai napon, a csakbaba<span>.hu</span> oldalon számlát állítottunk ki neked!</p>
<p>Egyenlegedet átutalással bankszámlára történő befizetéssel, és online bankkártyás fizetéssel töltheted fel ismét. Kérjük, hogy a zavartalan termékfeltöltés érdekében folyamatosan kísérd figyelemmel egyenleged alakulását!</p>

<p>Számlád részleteit a mellékletben csatolt számla letöltésével ill. az "Egyenlegem, számláim" menüpontban tekintheted meg. Számládat pdf formátumban küldjük, amelyet az ingyenesen letölthető AcrobatReader program segítségével tudsz megnyitni.</p>
<br />
<p>Köszönjük az együttműködésedet és, hogy igénybe vetted a csakbaba<span>.hu</span> szolgáltatásait!</p>
<br />
<p>Üdvözlettel,<br />
a csakbaba<span>.hu</span> csapata <br />
<a href="<?='https://'.$_SERVER['HTTP_HOST'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?></a></p>
