<p>Kedves <strong><?=$this->data['user']->username;?></strong>!<br /></p>
<br />
<p>A mai napon az alábbi terméket töltötted fel a csakbaba<span>.hu</span> oldalon:</p>
<ul>
	<li>Termék neve: <strong><?=$this->data['product']->name;?></strong></li>
	<li>Termék kódja: <strong><?=$this->data['product']->code;?></strong></li>
	<li>Ára: <strong><?=$this->data['product']->price;?> Ft.</strong></li>
	<li>Termék linkje: <br /><a href="<?='https://'.$_SERVER['HTTP_HOST'];?><?=$this->url('piac');?><?=$this->data['productlink'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?><?=$this->url('piac');?><?=$this->data['productlink'];?></a></li>
</ul>

<?php if(!empty($this->data['free'])){?>
    <p>Ne felejtsd el, hogy nálunk egyszerre összesen 10 terméket tölthetsz fel ingyenesen, továbbá, hogy terméked eladása esetén sem számítunk fel jutalékot!</p>
<?php } else { ?>
    <p>A termékfeltöltés díja az egyenlegedből levonásra került. Kérjük, hogy egyenlegedet folyamatosan kísérd figyelemmel, hogy a következő termékfeltöltésed is akadálytalan legyen. Ne felejtsd el, hogy terméked eladása esetén sem számítunk fel jutalékot!</p>
<?php } ?>
<p>Az eladás feltételeiről, a termékfeltöltés szabályairól, díjairól és egyéb díjtételeinkről az alábbi linken keresztül tájékozódhatsz:
<a href="<?='https://'.$_SERVER['HTTP_HOST'];?>/<?=$this->url('rolunk');?>">Mi az a csakbaba?</a></p>

<p>Köszönjük, hogy igénybe vetted a csakbaba<span>.hu</span> szolgáltatásait!</p>

<br />
<p>Üdvözlettel,<br />
a csakbaba<span>.hu</span> csapata <br />
<a href="<?='https://'.$_SERVER['HTTP_HOST'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?></a></p>
