<p>Kedves <strong><?=$this->data['user']->username;?></strong>!<br /></p>
<br />
<p>Értesítünk, hogy a mai napon csakbaba.hu oldalon az alábbi terméked lejárt státuszba került:</p>
<ul>
	<li>Termék neve: <?=$this->data['product']->name;?></li>
	<li>Termék kódja: <?=$this->data['product']->code;?></li>
	<li>Termék linkje: <br /><a href="<?='https://'.$_SERVER['HTTP_HOST'];?><?=$this->url('piac');?><?=$this->data['productlink'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?><?=$this->url('piac');?><?=$this->data['productlink'];?></a></li>
</ul>

<p>Emlékeztetünk, hogy az oldalunkra feltöltött termékeidet 30 napig tartjuk aktívan, utána a 31. napon lejárt státuszba helyezzük. Lehetőséged van a termékedet újra aktiválni (saját oldaladon egy kattintással), ennek költsége azonos a termékfeltöltési díj összegével. Kérjük, hogy a zavartalan termékfeltöltés érdekében folyamatosan kísérd figyelemmel az egyenleged!</p>
<br />
<p>Köszönjük az együttműködésedet és, hogy igénybe vetted a csakbaba.hu szolgáltatásait!</p>
<br />
<p>Üdvözlettel,<br />
a csakbaba<span>.hu</span> csapata <br />
<a href="<?='https://'.$_SERVER['HTTP_HOST'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?></a></p>
