<p>Kedves <strong><?=$this->data['user']['username'];?></strong>!<br /></p>
<br />
<p><strong>E-mail címed megváltoztatásához kattints az aktivációs linkre: </strong><br />
	<a href="<?=$this->data['activation_link'];?>"><?=$this->data['activation_link'];?></a>
</p>
<br />
<p>Üdvözlettel,<br />
a csakbaba<span>.hu</span> csapata <br />
<a href="<?='https://'.$_SERVER['HTTP_HOST'];?>"><?='https://'.$_SERVER['HTTP_HOST'];?></a></p>



