<div class="commentContainer">
  <div class="comments">
	  <ul>
		  <? foreach($this->comments as $comment){?>
				  <?=$this->partial('common/comment.phtml', array_merge($this->getVars(), array('comment'=>$comment)));?>
		  <? } ?>
	  </ul>
  </div>
	<div class="commentForm">
		<? if($this->user){?>
			<!--<ul>
				<li class="field checkbox commentSubscribe">
					<input type="checkbox" id="commentsubscribe" <?/*=(in_array($this->product->id, ($this->user->subscribed ?: array())) ? 'checked="checked"' : "");*/?> />
					<label for="commentsubscribe">Értesítést kérek ha hozzászólás érkezik</label>
				</li>
			</ul>-->
		<? } ?>
		<?=$this->commentForm;?>
	</div>
</div>