<div class="stat rolunk">
	<h1>Mi az a csakbaba?</h1>

	<img src="/img/elements/logo.png" />
	<p>
		A csakbaba.hu egy virtuális börze, vásár, amely összehozza az eladókat a vásárlókkal, és online „asztalt” biztosít a gondtalan adás-vételhez.
		A csakbaba.hu profilja tematikus, minden olyan termék eladható-megvehető nálunk, ami kismamával, babával vagy kisgyermekkel kapcsolatos függetlenül attól, hogy új vagy használt.
	</p>

	<p>
		Az oldal azért jött létre, hogy itt tényleg azt kapd, amit keresel, sőt, hogy itt csupán azt vedd meg, amiért eredetileg a gép elé ültél.
		Nálunk nem tudsz elkalandozni, ha a célod, hogy valamilyen kismama, baba vagy gyermekruhát, bútort, játékot vásárolj, mert nálunk nincs más.
		Viszont azon dolgozunk, hogy ebben a témában a lehető legszélesebb skálán mindent megtalálj!
	</p>

	<p>
		A csakbaba.hu-n nincs jutalék, csak feltöltési díj, melynek elsődleges célja a felhasználók, azaz a Te védelmed az ellenőrizetlen eladókkal szemben.
		A csakbaba.hu oldalt szintén biztonsági szempontok miatt csak regisztrált felhasználók használhatják.
	</p>

	<br /><br />




	<h3>Az ÁSZF, azaz a csakbaba.hu általános szerződési feltételei</h3>

	<p>
		Mint tudod az ÁSZF a mi saját szabályrendszerünk, melyet szakjogász készített el nekünk, így a benne foglaltak tartalmazzák a legaktuálisabb törvényi rendelkezéseket, jogszabályokat,
	  amelyek egy online vásártér működtetéséhez szükségesek. Az Általános szerződési feltételeket minden regisztrálónak ajánlott elolvasni, ennek megtörténtét regisztrációkor jelzed nekünk.
	  Tehát mi feltételezzük, hogy mindenki, aki regisztrál az oldalunkra és elfogadja az ÁSZF-ünket, el is olvasta azt, így a benne foglaltakat magára nézve kötelező érvényűnek tekinti.
	  Éppen ezért az ÁSZF-ben foglaltak megsértésekor tisztában vagy annak következményeivel, az esetleges szankciókkal, ezért jogorvoslatra elvben nincs lehetőség.
	</p>

	<p>
		Az ÁSZF nem csak bennünket, hanem Téged is véd. Védi az eladókat és védi a vásárlókat is, amennyiben az adás-vétel a csakbaba.hu oldalon történt, és ÁSZF-ünket betartottátok.
		Kérünk Téged, hogy a tisztességes, emberséges kereskedelem érdekében minden körülmények között tartsd be a csakbaba.hu felhasználói feltételeit, szabályait,
		mert egy esetleges reklamációt csak ennek fényében tudunk mérlegelni, elfogadni, bírálni.
	</p>

	<p>Soha ne feledd, hogy a regisztrációkor elfogadott ÁSZF megszegésének súlyos következményei is lehetnek!!! </p>

	<p>Az ÁSZF-et megtaláljátok a nyitólapon, illetve az alábbi linkre kattintva is:</p>

	<p><a href="<?=$this->url('aszf');?>">Általános szerződési feltételek</a></p>

	<br /><br />




	<h3>A vásárlás és az eladás </h3>

	<p>
		Ahhoz, hogy a csakbaba.hu oldalon felhasználó lehess, regisztrálnod kell az oldalon. A regisztráció ingyenes.
		Regisztrációkor csupán az alapadataidat szükséges megadnod, de ahhoz, hogy termékeket is adhass el az oldalon, ún. <strong>asztalt</strong> kell nyitnod,
		ehhez szükséges lesz a regisztrációdat egyéb adatokkal is kibővítened. Az <strong>asztalnyitás</strong> nem más, mint, hogy szeretnél termékeket feltölteni,
		de mi egy autentikus bababörzére gondolva, <strong>virtuális asztalokat</strong> bocsátunk részedre az eladáshoz.
		Tehát, ha úgy gondolod, hogy árusítani is szeretnél a csakbaba.hu-n, akkor kattints az <strong>asztalnyitás</strong> gombra.
	</p>

	<p><strong>Asztalt bármikor nyithatsz, nem kell azonnal a regisztrációkor. Viszont eladni csak akkor tudsz, ha már nyitottál asztalt! És ha feltöltötted az egyenleged!</strong></p>

	<br /><br />




	<h3>Eladás</h3>

	<p>
		Ahhoz, hogy az oldalon termékeket adhass el, asztalt kell nyitnod és fel kell töltened az eladói <strong>egyenlegedet</strong>, melynek minimum összege 320Ft.
		A feltöltési díj és az esetleges kiemeléseid minden esetben ebből az összegből kerülnek jóváírásra. Annyi terméket tudsz feltölteni, amennyi az egyenlegedre feltöltött összeg erejéig lehetséges.
		Az <strong>egyenlegedet</strong> tetszőlegesen <strong>bármekkora összeggel feltöltheted</strong>, a lényeg, hogy ez az összeg 320Ft-nál nem lehet kevesebb.
		A te felelősséged átgondolni, hogy mennyi terméked van, mennyit szeretnél feltölteni a csakbaba.hu oldalon, ugyanis a már feltöltött összeget visszafizetni nem áll módunkban,
		csak az ÁSZF-ben leírt körülmények esetén. A minimális feltöltés összege 8 termék feltöltésére elegendő, amennyiben semmilyen kiemelést nem kérsz a csakbaba.hu oldalon.
		A feltöltött összeg a feltöltéstől számított 1 évig áll a rendelkezésedre, ennyi időd van felhasználni az általad feltöltött összeget.
	</p>

	<p>
		Eladáshoz fontos tudnivaló, hogy terméket csak feltöltési díj ellenében tudsz az oldalon feltölteni. A feltöltési díj bruttó 40Ft/termék,
		amiért cserébe a termékeid 30 naptári napig lehetnek fent az oldalon, az asztalodon. Jutalékot semmilyen esetben sem számolunk fel, így tulajdonképpen nincs más költséged,
		ha eladni kívánsz, csak a feltöltési díj. Az oldalon különféle kiemelési lehetőségek állnak rendelkezésedre, ennek részleteit megtalálod lejjebb, a <strong>Kiemelések</strong> bekezdésben.
		A kiemelések minden esetben térítéskötelesek, ezekről is olvashatsz a <strong>Kiemelések </strong>bekezdésben.
	</p>

	<br /><br />




	<h3>Egyenleg feltöltés</h3>

	<p>Egyenleged feltöltése történhet átutalással, banki befizetéssel illetve kártyás fizetéssel PayU rendszerben közvetlenül az oldalunkon.</p>

	<p>
		Az átutalás és banki befizetés esetén a befizetett összeg beérkezésekor 24 órán belül megkapod a lehetőséget termékeid feltöltésére.
		Amennyiben ez 24 órán belül nem történik meg, úgy jelezd nekünk a megadott email címen (<a href="mailto:egyenleg-nospam(KUKAC)csakbaba.hu">egyenleg-nospam(KUKAC)csakbaba.hu</a>) és mi azonnal utánanézünk a problémának.
	</p>

	<p>Amennyiben kártyával töltöd fel egyenlegedet, úgy akár azonnal megkezdheted termékeid feltöltését a csakbaba.hu oldalon.</p>

	<p>
		Egyenleged alakulását folyamatosan végigkísérheted az <strong>egyenlegem, számláim</strong> menüpont alatt, ahol a számláidat is megtekintheted.
		Amikor egyenleged közelít a 40Ft felé, úgy értesítést küldünk erről emailben az általad megadott email elérhetőségre.
		Az időben fel nem töltött egyenleg kellemetlenségeket okozhat számodra, ha ismét szeretnél terméket feltölteni, és ezzel időt is veszíthetsz.
		Éppen ezért mi is kérünk, hogy kísérd figyelemmel az egyenleged alakulását!
	</p>

	<br /><br />




	<h3>Biztonság</h3>

	<p>
		Fontos tudnod, hogy a csakbaba.hu oldalt csak regisztrált felhasználók használhatják, ez minden esetben a felhasználók védelmében történik.
		Ezzel minimálisra csökkenthetjük annak a lehetőségét, hogy valaki nem megbízható eladóként vagy vásárlóként legyen jelen a csakbaba.hu oldalon.
	</p>

	<p>
		A feltöltési díjjal az eladók átesnek egyfajta ellenőrzésen, ezzel is tudjuk szűrni, hogy az eladói felhasználók mögött ténylegesen valós személyek állnak.
		Ugyanebből a megfontolásból kell nálunk előre kifizetni a feltöltéseket, azaz feltölteni az eladói egyenleget, amiből jóváírjuk a feltöltések, kiemelések összegét.
		Te, mint vásárló, így nagyobb biztonsággal börzézhetsz a csakbaba.hu oldalon.
	</p>

	<p>
		Az eladók az ÁSZF elfogadásával vállalják, hogy a termékfotók ténylegesen a termékoldalon a leírásban bemutatott terméket ábrázolják.
		Éppen ezért nálunk nem találkozol olyan termékkel, amelyről nincs fénykép, ugyanis a csakbaba.hu oldalon kép nélkül nem jelenhet meg termékhirdetés.
		Amennyiben a feltöltött termék illusztráció, úgy azt az eladó köteles a termék leírásában jelezni. Ezt szintén a vásárlás biztonsága érdekében alakítottuk így.
		Arra törekszünk, hogy tényleg azt kapd, amit a termékoldalon megvásároltál.
	</p>

	<p>
		Az egyenlegfeltöltéssel is az oldal felhasználóit, azaz Téged védünk, mert így az eladók ismét egyfajta ellenőrzésen esnek át, amivel tudjuk szűrni az illetéktelen felhasználók nagy részét.
		A vásárlók, Te nagyobb biztonsággal vásárolhattok az oldalon, mert tudjátok, hogy csak ellenőrzött felhasználók tölthetnek fel terméket az oldalra.
		A feltöltött termékekért a csakbaba.hu semmilyen körülmények között nem vállal felelősséget, aki azonban nem az ÁSZF-ben meghatározott terméktípusokat tölti fel oldalunkra,
		az vét a csakbaba.hu oldal felhasználási szabályai ellen, és mint ilyen, azonnal inaktiváljuk a termékeit, a felhasználót pedig kizárjuk az oldalról.
		Kérünk Téged, hogy az ÁSZF-ben meghatározott és a regisztrációkor általad is elfogadott szabályokat minden körülmények között tartsd be, amikor a csakbaba.hu oldalra látogatsz.
	</p>

	<br /><br />





	<h3>Adataid</h3>

	<p>
		Az adataim menüpontban az adataidat bármikor megváltoztathatod, amennyiben valamely adatodban változás történt.
		Ezen kívül tölthetsz fel tetszőleges képet, amely a te felhasználói profil képed lesz a későbbiekben.
		Ha kedved van, akkor pár szót írhatsz magadról, az asztalodról, a termékeidről, egyfajta bemutatkozásként. <strong>A profilod</strong> tükrözheti az asztalod egyediségét, a termékeid sajátosságát, téged.
		Ezt egyfajta reklámként is értelmezheted, ez<strong> a te asztalod marketingje</strong>. Ebben írhatsz a szállításról is, annak díjairól, a vásárlás feltételeiről, stb. <strong>Élj vele! </strong>
	</p>

	<br /><br />




	<h3>Üzenetek</h3>

	<p>
		Az eladó és a vásárló közötti kommunikációra a termékoldalon elhelyezett üzenőfalon van lehetőség. Üzenetet az <strong>Kérdések az eladóhoz </strong>gombra kattintva tudsz küldeni.
		Üzeneteidet a többi felhasználó is látja, így még több információhoz juthatnak a termékről.
	</p>

	<p>
		Az üzenetek tartalmára vonatkozó, az ÁFSZ-ben is megtalálható rendelkezésünket minden esetben tartsd be, tehát az üzenőfalon az üzenetek tartalma kizárólag csak az adott oldalon feltöltött termékre vonatkozhat.
		Tilos egymás elérhetőségét, nevét, telefonszámát, címét, stb. az üzenőfalon elkérni, a sajátotokat megadni, mert az a felhasználói oldalatok felfüggesztését vonja maga után.
	</p>

	<br /><br />




	<h3>Termékfotók</h3>

	<p>
		A termékeid eladhatóságának hatékonyságát növelheted azzal, ha a termékeidről igényes fényképet készítesz.
		Egy szép, világos, éles fotó a termékedről figyelem felkeltőbb a vásárlók számára, így nagyobb esélyed van arra, hogy termékedet mihamarabb eladd.
		Kérünk Téged, hogy a fotó azt a terméket ábrázolja, amelyről a leírásban is írsz. Törekedj arra, hogy a terméked állapotát, minőségét a fotó a lehető legjobban tükrözze.
		A termékfotókról és az ezzel kapcsolatos szabályainkról az Általános szerződési feltételekben olvashatsz további részleteket.
	</p>

	<br /><br />




	<h3>Feltöltési díjaink, kiemelések</h3>

	<p>A csakbaba.hu oldalon 10 db aktív termék feltöltéséig ingyenes, e fölötti terméket csak feltöltési díj ellenében tudsz feltölteni.</p>
	<p>A termékeladáshoz más költséged nem lesz, mert a csakbaba.hu nem számol fel jutalékot az eladások után.</p>

	<p>Termékeid kiemelésére is lehetőséged van az oldalunkon, ezt térítés ellenében kérheted. <strong>Termékkiemelést</strong> már feltöltött termék esetében is kérhetsz az <strong>asztalom</strong> menüpontban.</p>

	<p>
		A csakbaba.hu oldalon az asztalnyitáshoz fel kell töltened az egyenleged. Ennek minimum összege 320Ft, mely 8 termék feltöltésére ad lehetőséget (amennyiben kiemeléseket nem kértél).
	  Az egyenlegedet bármilyen általad megfelelőnek tartott összeggel feltöltheted, de az összeg nem lehet kevesebb, mint 320Ft.
	  Az utalásod költségeit vedd figyelembe, mert egy egyszeri nagyobb egyenlegfeltöltéssel spórolhatsz is magadnak!
	</p>

	<br /><br />




	<h3>Díjak</h3>

	<p>Termékfeltöltés: 40Ft/termék/30 nap (a termékfeltöltés 10 aktív termék feltöltéséig ingyenes)</p>

	<p>Kiemelések:</p>

	<ul>
		<li>Kiemelés kerettel: 120Ft/termék/hét</li>
		<li>Lista elejére kerülés: 160Ft/termék/hét</li>
	</ul>

	<p>Nyitólapra kerülés:</p>

	<ul>
		<li>kiemelt termékként: 520Ft/hét</li>
		<li>Asztalom reklám 960Ft/hét</li>
	</ul>

	<br /><br />




	<h3>Hírlevél</h3>

	<p>
		Regisztrációkor lehetőséged van bejelölni, hogy kérsz-e hírlevelet tőlünk vagy sem. A hírlevél mindig aktuális érdekességeket, információkat, akciókat tartalmaz.
		Annak érdekében, hogy mindig időben értesülj újdonságainkról, híreinkről, és ez által akár az eladásaid hatékonyságát növeld, érdemes a hírlevelünkre feliratkoznod.
		Hírlevelünkben lehetőséged lesz reklámozni az Asztalod, így igen sok felhasználóhoz eljuthat az Asztalod híre. Erre térítés ellenében lesz lehetőséged.
	</p>

	<br /><br />




	<h3>Blog</h3>

	<p>
		Rendszeres blog bejegyzéseinket olyan témákban írjuk, melyek tükrözik az oldal tematikáját. Olvashatsz majd gyermeknevelésről, terhességről, a különböző termékek teszteléseiről,
		bölcsődékről, óvodai nevelésről, stb. Témáink tárháza kimeríthetetlen. Neked írjuk ezeket, bízva abban, hogy megtalálod a számodra érdekes gondolatokat mindegyikben.
		Blog témajavaslataidat szívesen fogadjuk a <a href="mailto:blog-nospam(KUKAC)csakbaba.hu">blog-nospam(KUKAC)csakbaba.hu</a> email címen.
	</p>

	<br /><br />




	<h3>Adatvédelem</h3>

	<p>
		Adataid védelmét az Általános szerződési feltételeink is tartalmazzák. Adatait kezelésére a mindenkori törvényi rendelkezéseket alkalmazzuk.
		Adatvédelmi nyilatkozatunkat az Adatvédelmi hatóság nyilvántartásba vette.
	</p>

	<br /><br />

	<p>Jó börzézést kívánunk!</p>

	<p>A csakbaba.hu csapata</p>

	<p> </p>

</div>