<div class="stat aszf">
<h1>Általános szerződési feltételek</h1>

<p> </p>

<h2><strong>I. Általános rendelkezések</strong></h2>

<p> </p>

<h3><em>I/1. Az Üzemeltető személye</em></h3>

<p>Jelen weboldalt a <strong>Csakbaba.hu Korlátolt Felelősségű Társaság</strong> (székhely: 2119 Pécel, Szent Imre krt. 53. A. ép.; cégjegyzékszám: 13-09-130160; e-mail: <a href="mailto:info-nospam(KUKAC)csakbaba.hu">info-nospam(KUKAC)csakbaba.hu</a>, a továbbiakban: Üzemeltető) üzemelteti. A weboldalon a felhasználók által megadott személyes adatokat az Üzemeltető kezeli.</p>

<p> </p>

<h3><em>I/2. A felhasználó</em></h3>

<p>Felhasználó minden olyan személy, aki a weboldalt meglátogatja, annak szolgáltatásait igénybe veszi. Felhasználónak minősülnek azon személyek is, akik a honlapon nem regisztrálnak, keresést nem végeznek, terméket nem árulnak és nem is vásárolnak. Bizonyos adatkezelések és feltételek csak regisztrált, vagy a szolgáltatást ténylegesen igénybe vevő felhasználókra vonatkoznak.</p>

<p> </p>

<h3><em>I/3. A szabályzat hatálya és módosítása</em></h3>

<p>Jelen Felhasználási és adatkezelési szabályzat (továbbiakban: Szabályzat) hatálya az Üzemeltető <a href="http://www.csakbaba.hu/">www.csakbaba.hu</a> weboldalhoz (továbbiakban: Weboldal) kapcsolódóan nyújtott szolgáltatásaira és adatkezeléseire terjed ki.</p>

<p>Ellenkező kikötés hiányában a Szabályzat hatálya nem terjed ki azon szolgáltatásokra és adatkezelésekre, melyek a Weboldalon hirdető, vagy azon más módon megjelenő harmadik személyek promócióihoz, nyereményjátékaihoz, szolgáltatásaihoz, egyéb kampányaihoz, az általuk közzétett tartalomhoz kapcsolódnak. Ellenkező kikötés hiányában a Szabályzat hatálya nem terjed ki olyan weboldalak, szolgáltatók szolgáltatásaira és adatkezeléseire, melyekre a jelen <a href="file:///C:/Documents%20and%20Settings/Felhaszn%C3%A1l%C3%B3/Local%20Settings/Temp/www.book.hu">../../../Documents and Settings/Felhasználó/Local Settings/Temp/www.book.hu</a>Weboldalon található hivatkozás vezet.</p>

<p>A Szabályzat módosításának jogát az Üzemeltető fenntartja. Az Üzemeltető kérésre tájékoztatja a felhasználókat a korábbi módosításokról. Az Üzemeltető a módosított szabályzatot közzéteszi, a módosítások csak a közzétételt követően hatályosak. Az Üzemeltető nem köteles arra, hogy a módosításokról külön értesítést küldjön a felhasználók részére.</p>

<p> </p>

<h3><em>I/4. Az Üzemeltető tevékenysége, a weboldal célja</em></h3>

<p>Az Üzemeltető természetes személy felhasználók közötti kereskedést lehetővé tevő Weboldalt tart fenn. Jelen Weboldal célja, hogy a felhasználók a használt, megunt, mérethibás, nem tetsző, vagy bármilyen más okból értékesíteni kívánt kismama-, baba- és gyermekruháikat, játékaikat, egyéb, csecsemőkkel, kisgyermekekkel kapcsolatos árucikkeiket (játékok, babaápolási termékek, bútorok stb.) értékesíthessék. A felhasználók az értékesíteni kívánt árucikkeket a jelen Szabályzatban meghatározottak szerint feltölthetik az oldalra, így a vásárolni kívánó felhasználók az értékesítővel kapcsolatot tudnak létesíteni.</p>

<p>A Weboldal az értékesíteni kívánt áruk közzétételére biztosít felületet, az értékesítésben az Üzemeltető nem vesz részt.</p>

<p> </p>

<h3><em>I/5. Irányadó jog</em></h3>

<p>Az Üzemeltető a Magyarországon bejegyzett gazdasági társaság, amely tevékenységét elsősorban a magyar jogszabályok hatálya alatt végzi. Amennyiben az Üzemeltető tevékenysége – ide értve a reklámozási tevékenységet is – Magyarország határain túlra irányul, a célország joga megfelelően irányadó, azzal, hogy ha valamely jog alkalmazása kiköthető, az Üzemeltető kiköti a magyar jog alkalmazását.</p>

<p>Arra az esetre, ha joghatóság kikötésének helye van, az Üzemeltető kiköti a magyar hatóságok és bíróságok joghatóságát.</p>

<p> </p>

<h3><em>I/6. A szolgáltatás folyamatossága</em></h3>

<p>Az Üzemeltető vállalja, hogy minden tőle elvárható intézkedést megtesz a szolgáltatás zavartalansága és folyamatossága érdekében. Az Üzemeltető nem szavatolja a szolgáltatás szünetmentességét, nem tehető felelőssé továbbá a szolgáltatás felfüggesztéséért vagy megszüntetéséért. Az Üzemeltető az oldal működése során előálló esetleges zavarok, működési problémák elhárítására törekszik, azokért azonban felelőssé nem tehető.</p>

<p>Az Üzemeltető a felhasználók magatartásáért felelősséget nem vállal.</p>

<p>Az Üzemeltető minden szükséges intézkedést megtesz a felhasználók adatainak biztonsága érdekében.</p>

<p> </p>

<h2><strong>II. Az értékesítési tevékenység, a szolgáltatás igénybe vétele</strong></h2>

<p> </p>

<h3><em>II/1. A keresés, értékesítés folyamata, az értékesíthető áruk köre</em></h3>

<p>Az oldal regisztráció nélkül szabadon látogatható. A regisztráció nélküli felhasználók kereshetnek az értékesítésre felkínált árucikkek között.</p>

<p>Az értékesítésre és vásárlásra csak a regisztrált felhasználók jogosultak. A regisztráció során a felhasználónak meg kell adni a regisztrációs űrlapon szereplő adatait, valamint el kell fogadnia jelen Szabályzatot. A regisztráció során a felhasználó hozzájárul személyes adatainak a jelen Szabályzat III. fejezete szerinti kezeléséhez.</p>

<p>A regisztrált felhasználó jogosult arra, hogy egyenlegét feltöltse, és a feltöltött egyenleget felhasználja árucikkek feltöltésére. Egy árucikk feltöltése bruttó 40,- Ft, amely tartalmazza az általános forgalmi adót. A kereskedelmi forgalomban önállóan kapható, jellemzően önállóan használt árucikkek külön árucikknek minősülnek akkor is, ha bizonyos szempontok szerint összekapcsolódnak (pl. kiságy és pelenkázóasztal). Egy árucikknek minősülnek a rendeltetésüknél fogva összetartozó tárgyak (pl. pelenkázóasztal és pelenkázólap, kiskád, és a kiskád lábazata), valamint azok az árucikkek, amely megjelenésüknél, alkalmazási körüknél fogva szorosan összekapcsolódnak, és az értékesítésre a kereskedelmi forgalomban is jellemzően együtt kerül sor (pl. ugyanazon figurákkal díszített, egybetartozó sapka és egyéb ruházat). Egy árucikk csak egy áron értékesíthető, az egy árucikként feltöltött tárgyak nem bonthatók meg, külön ár nem határozható meg az egyes tárgyakra.</p>

<p>Az egyenleg feltöltése előre fizetéssel történik. Az egyenleg feltöltését követően a felhasználó jogosult a feltöltött egyenleg erejéig árucikk feltöltésére. A felhasználó köteles képet, az értékesítésre kínált árucikkről leírást közzétenni. A feltöltött kép kizárólag az értékesítésre kerülő árucikket mutathatja. Amennyiben a kép nem a ténylegesen értékesítésre kerülő árucikket mutatja be (pl. gyártó, forgalmazó oldaláról átvett kép), ebben az esetben ezt a tényt közölni kell, a „kép illusztráció” megjelöléssel. A felhasználó közzéteszi az árucikk árát.</p>

<p>A felhasználó nem tehet közzé utalást más, a Weboldalon értékesítésre nem kínált árucikkek eladására. Sem a felhasználó által feltöltött kép, sem az árucikkről szóló ismertető nem reklámozhatja felhasználó, vagy harmadik személy termékét, szolgáltatását, és nem tartalmazhat ezekre közvetve sem utalást (pl. értékesítő honlapjának, felhasználó más weboldalának feltüntetése).</p>

<p>A feltöltött árucikk a feltöltést követően 30 napig szerepel a Weboldalon. 30 nap elteltével az árucikk törlésre kerül, akkor is, ha nem kerül értékesítésre. A felhasználó az el nem adott árucikket újból feltöltheti, ebben az esetben a feltöltés díját újból meg kell fizetnie.</p>

<p>A vásárolni kívánó felhasználók az oldalon értékesítésre kínált árucikkek között szabadon kereshetnek. Amennyiben valamely árucikket meg kívánják vásárolni, regisztrációt követően a Weboldalon keresztül kapcsolatba léphetnek az eladóval, a Weboldal felületén keresztül. Ezen kommunikáció során a felek adataikat egymásnak nem adhatják meg, az értékesítést nem bonyolíthatják. A vásárló csak abban az esetben kapja meg az értékesítő adatait, ha az árucikk megvásárlásáról nyilatkozik. Ezt követően a felek szabadon egyeztetnek a szállítás és fizetés szabályairól. Amennyiben az értékesítő közzétette, hogy az árucikket milyen módon lehet átvenni és megfizetni, a vásárló azt elfogadja, amikor nyilatkozik az árucikk megvásárlásáról.</p>

<p>A vásárló köteles a megvásárolt árucikket az egyeztetett módon átvenni és megfizetni. Amennyiben a vásárló ezt megtagadja, az Üzemeltető jogosult a vásárlót az oldalról kitiltani.</p>

<p>Amennyiben az árucikk értékesítésre került, a felhasználó köteles azt törölni az értékesítésre szánt árucikkek közül. A felhasználó szabadon törölheti az árucikket az értékesítést megelőzően is.</p>

<p>Amennyiben a felhasználó a regisztrációját törli, vagy a törlésre a jelen Szabályzat rendelkezéseinek megsértése miatt kerül sor, a feltöltött árucikkek is törlésre kerülnek.</p>

<p>A Weboldalon kizárólag kismama, és tíz év alatti gyermekek által használt, vagy a gyermekek nevelésével, oktatásával, ápolásával, fejlesztésével, szállításával kapcsolatos árucikkek forgalmazhatók. Nem forgalmazhatók a Weboldalon gyógyszerek, orvosi rendelvényre kapható, vagy egészségügyi személyzet felügyelete mellett használható gyógyászati segédeszközök, továbbá más olyan árucikkek, amelyek forgalmazása engedélyhez kötött. Nem forgalmazhatók életre, testi épségre, egészségre ártalma árucikkek. Amennyiben valamely árucikk biztonságos használatához használati utasítás szükséges, a forgalmazás csak a használati utasítással együtt lehetséges. A szabályoknak nem megfelelő árucikkeket az Üzemeltető törölheti.</p>

<p> </p>

<h3><em>II/.2. Egyenleg feltöltése, fizetés, visszatérítés</em></h3>

<p>Az Üzemeltető minden esetben meghatározza az egyes árucikkek feltöltésének árát. Egy árucikk feltöltése bruttó 40,- Ft, amely tartalmazza az általános forgalmi adót. Az Üzemeltető egyéb szolgáltatásokat is biztosíthat (pl. kiemelés), amelynek díját minden esetben előre meghatározza, és a Weboldalon feltünteti.</p>

<p>Az egyenleg feltöltése legalább 320,- Ft összegre lehetséges. Az Üzemeltető szabadon határozza meg, hogy mely módokon (bankkártya, sms, paypal, stb.) lehet az egyenleget feltölteni. A felhasználó a feltöltés összegének az Üzemeltetőhez történő megérkezését követő legfeljebb 24 óra elteltével jogosult az egyenlegével rendelkezni. Amennyiben a felhasználó egyenlege csökken, jogosult egyenlegének újbóli feltöltésére.</p>

<p>A felhasználó egyenlegéből minden egyes árucikk feltöltésekor, vagy egyéb szolgáltatás igénybe vételekor levonásra kerül a feltöltés díja. A díj akkor is levonásra kerül, ha a felhasználó az értékesítéstől elállt, és az árucikket törölte, vagy ha az árucikket az Üzemeltető törölte, a jelen Szabályzat megsértése miatt.</p>

<p>A feltöltött egyenleg a feltöltéstől számított egy éven belül használhatók fel. Amennyiben a felhasználó a regisztrációját törli, vagy a törlésre a jelen Szabályzat rendelkezéseinek megsértése miatt kerül sor, a feltöltött egyenleg is elvész, ebben az esetben a felhasználó visszatérítésre, újbóli regisztráció esetén a fel nem használt egyenleg „aktiválására” nem jogosult. Felhasználó kifejezetten elfogadja, hogy az egyenleg fel nem használt részére az Üzemeltető átalány díjként jogosult, figyelemmel arra, hogy a felhasználó az Üzemeltető szolgáltatásait abban az esetben is igénybe veszi, ha nem használja fel a teljes egyenlegét.</p>

<p>Az Üzemeltető jogosult az árucikkek feltöltési díjának megváltoztatására.</p>

<p>A felhasználó az egyenlegen fel nem használt összeg visszatérítésére kizárólag abban az esetben jogosult, ha az értékesítés az Üzemeltetőnek felróható okból lehetetlenül el, vagy ha a felhasználó a feltöltési díj emelése miatt a szerződést felmondja, regisztrációját törli, és az egyenlegén lévő összeget visszakéri.</p>

<p> </p>

<h3><em>II/3. Üzemeltető szerepe az értékesítésben, ellenőrzés, az Üzemeltető felelősségének kizárása</em></h3>

<p>Az Üzemeltető az értékesítéshez kizárólag azt a felületet biztosítja, amelyen a felhasználók az értékesítésre szánt árucikkeket értékesítésre fel tudják kínálni. Az Üzemeltető értékesítési tevékenységet nem folytat, az adásvételben semmilyen módon nem vesz részt.</p>

<p>Az Üzemeltető az értékesítési tevékenységet rendszeresen ellenőrzi.</p>

<p>Az Üzemeltető az értékesítésre kínált árucikkekkel, az értékesítő személyével kapcsolatban semmilyen felelősséget nem vállal. A vásárló az Üzemeltetővel szemben szavatossági igényt nem érvényesíthet.</p>

<p>Az Üzemeltető nem vállal felelősséget azért, hogy a Weboldalon a felhasználók által közzétett információk pontosak, teljesek, és időszerűek. A Weboldalon közzétett információk nem minősülnek ajánlatnak az Üzemeltető részéről. Az Üzemeltető nem vállal felelősséget azért, hogy a Weboldalon megjelenő árucikkek ténylegesen elérhetők. A Weboldalon közzétett információk semmilyen módon nem tekinthetők az Üzemeltető szerződéses nyilatkozatainak, hivatalos tájékoztatóknak, használati utasításoknak.</p>

<p>A Weboldalon közzétett információk megismerése nem váltja ki az árucikkek használatára, igénybe vételére vonatkozó hivatalos tájékoztatások megismerését, szakember segítségének igénybe vételét.</p>

<p> </p>

<h3><em>II/4. Az adásvétellel létrejövő jogviszony</em></h3>

<p>Az adásvétellel a jogviszony minden esetben az értékesítő és a vásárló felhasználó között jön létre. A jogviszonyból származó jogok és kötelezettségek ezen felhasználókat illetik, illetve terhelik. A felhasználók a jogviszonyból származó igényeiket kizárólag az adott jogviszonyban szereplő másik felhasználóval szemben érvényesíthetik.</p>

<p> </p>

<h3><em>II/5. Kereskedők részvétele</em></h3>

<p>Kereskedelmi tevékenységgel üzletszerűen foglalkozó jogalanyok (Kereskedők) részvételét az Üzemeltető egyedi feltételekhez kötheti. A Kereskedőktől az Üzemeltető kérheti annak igazolását, hogy kereskedelmi tevékenységre jogosultak. A Kereskedők a Weboldalon bármilyen közleményt, tájékoztatást kizárólag a fogyasztók védelmére és a reklámozásra vonatkozó szabályoknak megfelelően helyezhetnek el. A Kereskedő árucikk leírását köteles úgy közzétenni, hogy az megfeleljen a reklámozási tevékenységre vonatkozó valamennyi jogszabálynak és etikai szabálynak.</p>

<p>A Kereskedő köteles a felhasználókat az irányadó szabályok szerint tájékoztatni a kereskedői minőségéről, adatairól, a felhasználó jogairól.</p>

<p>A Kereskedők a regisztrációval egyidejűleg kötelesek tájékoztatni az Üzemeltetőt e-mailen a regisztrációról, és arról, hogy az oldalon kereskedői minőségben értékesítési tevékenységet kívánnak folytatni.</p>

<p>Az Üzemeltető a Kereskedők részvételét korlátozhatja, kizárhatja, vagy további, jelen Szabályzattól eltérő feltételhez kötheti. Amennyiben valamely Kereskedő korlátozására vagy kizárására anélkül kerül sor, hogy a Kereskedő jogszabály, vagy jelen Szabályzat rendelkezéseit sértené, jogosult az egyenlegén szereplő összeg visszatérítésére.</p>

<p>A Kereskedő a kereskedelmi tevékenységéért önállóan, az irányadó jogszabályok szerint felel.</p>

<p> </p>

<h3><em>II/6. Kártérítési felelősség</em></h3>

<p>A felhasználók – ide értve a Kereskedőket is – az értékesítési tevékenységük során az Üzemeltetőnek, vagy harmadik személynek okozott kárért teljes körű és korlátlan felelősséggel tartoznak. A kártérítési kötelezettség kiterjed az elmaradt haszonra és az Üzemeltető, vagy harmadik személy jó hírnevének megsértésével okozott kárra is.</p>

<p> </p>

<h2><strong>III. Adatkezelés</strong></h2>

<p> </p>

<h3><em>III/1. Az adatkezelés jogalapja és elvei</em></h3>

<p>A személyes adatok kezelője az Üzemeltető.</p>

<p>Az adatkezelés jogalapja az érintettek önkéntesen megadott hozzájárulása. Az érintettek a regisztráció során elfogadják jelen Szabályzatot, és hozzájárulnak személyes adataik jelen Szabályzat szerinti kezeléséhez. Jelen Szabályzat az érintett tájékoztatásának minősül.</p>

<p>Az Üzemeltető kizárólag az érintett által megadott, valamint az érintett értékesítési, vásárlási tevékenységével kapcsolatos adatokat (értékesítésre feltöltött termékek, értékesítés gyakorisága, értékesítéssel kapcsolatos aktivitás, egyenleg feltöltése), valamint az érintett Weboldallal összefüggő tevékenysége során keletkezett személyes adatokat kezeli.</p>

<p>Az Üzemeltető törekszik arra, hogy a személyes adatok kezelésének alábbi elvei maradéktalanul érvényesüljenek:</p>

<p>-    személyes adat kezelésére csak meghatározott célból kerül sor;</p>

<p>-    az adatkezelés minden szakaszában megfelel ezen célnak, ide értve a kezelt adatkört is;</p>

<p>-    a személyes adatok felvétele és kezelése tisztességes és törvényes;</p>

<p>-    az adatok pontosak, teljesek és időszerűek;</p>

<p>-    ha az érintett azonosítása nem szükséges, az adatkezelés úgy módosul, hogy az érintettet az adat alapján azonosítani ne lehessen;</p>

<p>-    az érintettek jogai megfelelően érvényesülnek.</p>

<p> </p>

<h3><em>III/2. Az adatkezelés helye, irányadó jog</em></h3>

<p>A személyes adatok kezelése az Üzemeltető székhelyén, fióktelepén, telephelyén, vagy az Üzemeltető által megbízott adatfeldolgozó helyiségében történik. Az adatkezeléssel kapcsolatos döntéseket az Üzemeltető hozza meg.</p>

<p>Figyelemmel az I/5. pontban foglaltakra, az adatkezelő magyar jogi személy, az adatkezelés helye Magyarország. Mindezek alapján a személyes adatok kezelésére a magyar jogszabályok, elsősorban az információs önrendelkezési jogról és az információszabadságról szóló 2011. évi CXII. törvény szabályai az irányadók.</p>

<p>Az Üzemeltető az adatkezelés során figyelembe veszi az Európai Parlament és a Tanács személyes adatok feldolgozása vonatkozásában az egyének védelméről és az ilyen adatok szabad áramlásáról szóló 95/46/EK irányelvének rendelkezéseit.</p>

<p> </p>

<h3><em>III/3. Regisztráció</em></h3>

<p>A Weboldal látogatása regisztrációhoz nem kötött, értékesítésre azonban csak regisztrált felhasználók jogosultak. A regisztráció a Weboldalon lehetséges, a regisztrációs űrlap kitöltésével.</p>

<p>A regisztráció során az érintett megadja az azonosításhoz és a kapcsolattartáshoz szükséges adatait (név, e-mail cím, telefonszám), valamint a számlázáshoz szükséges adatokat, továbbá az Üzemeltető által megjelölt egyéb adatokat. A regisztrációs űrlapon kötelezőként megjelölt adatok megadása a sikeres regisztráció feltétele.</p>

<p>A regisztrációt követően az Üzemeltető megerősítő linket küld az érintett részére, ennek segítségével véglegesíthető a regisztráció. A regisztráció véglegesítését követően az Üzemeltető a jelen Szabályzatban meghatározottak szerint kezeli az érintettek adatait.</p>

<p>A regisztráció lehetséges Facebook vagy Google fiók használatával is. Ebben az esetben az Üzemeltető automatikusan átveszi a felhasználó bejelentkezési nevét és e-mail címét.</p>

<p> </p>

<h3><em>III/4. A személyes adatok kezelésének célja </em></h3>

<p>A regisztráció során megadott adatok kezelésének elsődleges célja a felhasználó azonosítása, a felhasználó vásárlásainak kezelése, a fizetési rendszer működtetése, a Weboldal szolgáltatásainak nyújtása, valamint a szolgáltatások fejlesztése. Az adatkezelés célja az érintettek azonosítása, valamint a velük való kapcsolattartás. Az adatok kezelésének célja ezen túlmenően az érintettek részére hírlevelek és reklámok küldése, az alábbiakban meghatározottak szerint.</p>

<p> </p>

<h3><em>III/5. Hozzáférés a kezelt adatokhoz, adattovábbítás, az adatok felhasználása</em></h3>

<p>Az adatokhoz az Üzemeltető érdekkörében eljáró azon személyek – így különösen megbízottak, munkavállalók – férnek hozzá, akiknek ez tevékenységük ellátásához szükséges, és akik az adatok kezelésével kapcsolatos kötelezettségekkel tisztában vannak.</p>

<p>A kezelt adatokat az Üzemeltető csak abban az esetben továbbítja, vagy teszi hozzáférhetővé harmadik személyek számára, ha ehhez az érintett kifejezetten hozzájárult, vagy ezt törvény elrendeli.</p>

<p>Az Üzemeltető az irányadó jogszabályoknak megfelelően jogosult arra, hogy egyes technikai műveletek céljára adatfeldolgozót vegyen igénybe. Az adatfeldolgozó csak az Üzemeltető döntéseinek végrehajtására jogosult, az Üzemeltető utasításainak megfelelően. Az adatfeldolgozó igénybe vétele az Üzemeltető felelősségét nem érinti.</p>

<p>Az Üzemeltető jogosult arra, hogy az adatokat személyazonosításra alkalmatlan módon statisztikai célra felhasználja.</p>

<p> </p>

<h3><em>III/6. Reklámozási és kutatási célú adatkezelés</em></h3>

<p>Az Üzemeltető jogosult arra, hogy az érintett megadott elérhetőségeit (e-mail címét, postai címét, telefonszámát, egyéb, kapcsolattartásra használt azonosítóit) felhasználja arra a célra, hogy részére az Üzemeltetővel, az Üzemeltető tevékenységével összefüggő promóciós célú elektronikus levelet, a szolgáltatással összefüggő hírlevelet, vagy reklámot tartalmazó levelet küldjön, számára ilyen célú tájékoztatást juttasson el. Az érintett kifejezetten hozzájárul ahhoz, hogy az Üzemeltető a tájékoztatásban, hírlevélben, illetve az egyéb értesítő levélben reklámot helyezzen el.</p>

<p>A regisztrációval az érintett kifejezetten hozzájárul ahhoz, hogy számára az Üzemeltető a közvetlen megkeresés módszerével reklámot küldjön, és ebből a célból megadott adatait felhasználja. A hozzájárulás az e-mailben, telefonon, a postai úton, valamint az egyéb módon történő megkeresésre egyaránt vonatkozik.</p>

<p>Az érintettek hozzájárulnak ahhoz, hogy a weboldal használata során keletkezett adatokat az Üzemeltető reklámozási célra felhasználja annak érdekében, hogy az érintettek számára célzott, a címzettet érintő ajánlatokat juttathasson el. A kezelt adatokat az Üzemeltető felhasználhatja a letöltött oldalakon megjelenő hirdetési felületek személyre szabására, valamint a kilépéskor betöltendő oldal kiválasztására. Ezen műveletek automatikusan, emberi beavatkozás nélkül, számítástechnikai program által történnek.</p>

<p>A kezelt adatokat az Üzemeltető felhasználhatja közvélemény-kutatás, piackutatás céljára, kutatási minta összeállítására, az érintettek ilyen célú megkeresésére.</p>

<p>A felhasználó a hírlevelek és reklámok küldését megtilthatja.</p>

<p> </p>

<h3><em>III/7. Az adatkezelés időtartama</em></h3>

<p>Az Üzemeltető a megadott adatokat törli, ha:</p>

<p>-    azok kezelése jogellenes, vagy jogszabály a törlést elrendeli;</p>

<p>-    az érintett azt kéri;</p>

<p>-    az adat hiányos vagy téves, és ez a felhasználásukat lehetetlenné teszi;</p>

<p>-    az adatkezelés célja megszűnt;</p>

<p>-    azt hatóság vagy bíróság elrendeli.</p>

<p>Az érintett kérheti személyes adatai törlését. Az érintett erre irányuló kérése esetén az adatokat az Üzemeltető rendszere öt munkanapon belül törli. A személyes adatok törlése során az adatok felismerhetetlenné tételére kerül sor, oly módon, hogy az adat és az érintett közötti kapcsolat többé ne legyen helyreállítható.</p>

<p>Amennyiben az érintett és az Üzemeltető között polgári jogi jogviszony jön létre (pl. szavatossági igény), az adatok kezelésére a polgári jog szabályai is irányadók. Ebben az esetben a személyes adatok polgári jogi igények érvényesítése érdekében kezelhetők. Amennyiben az érintett jogellenes cselekménye miatt hatósági vagy bírósági eljárás indul, ennek eredményes lezárása érdekében az Üzemeltető az adatokat kezelheti.</p>

<p> </p>

<h3><em>III/8. Az érintettek jogai, a magánszféra védelme</em></h3>

<p>Az érintettnek jogában áll, hogy adatait helyesbítse, a tévesen szereplő, és általa nem helyesbíthető adatok helyesbítését az Üzemeltetőtől kérje. Az érintett joga, hogy egyes adatait, vagy teljes regisztrációját törölje. Az érintett tájékoztatást kérhet adatai kezeléséről. A tájékoztatást az Üzemeltető elektronikus levélben is megadhatja. Az érintett tiltakozhat személyes adatai kezelése ellen.</p>

<p> </p>

<h3><em>III/9. Adatbiztonság</em></h3>

<p>Az Üzemeltető minden tőle elvárható szükséges intézkedést megtesz az adatok biztonsága érdekében, gondoskodik azok megfelelő szintű védelméről különösen a jogosulatlan hozzáférés, megváltoztatás, továbbítás, nyilvánosságra hozatal, törlés vagy megsemmisítés, valamint a véletlen megsemmisülés és sérülés ellen.</p>

<p>Az Üzemeltető az adatok biztonságáról megfelelő technikai és szervezési intézkedésekkel gondoskodik.</p>

<p> </p>

<h3><em>III/10. Adatok kezelése technikai célból</em></h3>

<p>Az Üzemeltető rendszere automatikusan rögzíti az érintett számítógépének IP-címét, a látogatás kezdő időpontját, illetve egyes esetekben – a számítógép beállításától függően – a böngésző és az operációs rendszer típusát. Az így rögzített adatok egyéb személyes adatokkal nem kapcsolhatók össze. Az adatok kezelése kizárólag statisztikai célokat szolgál.</p>

<p> </p>

<h3><em>III/11. Nemzeti Adatvédelmi és Információszabadság Hatóság</em></h3>

<p>Az Üzemeltető az adatkezelést az adatvédelmi biztos által vezetett nyilvántartásba bejelentette. Az adatkezelés nyilvántartási számát az Üzemeltető annak kézhezvételét követően közzéteszi.</p>

<p> </p>

<h2><strong>IV. A felhasználókra irányadó szabályok</strong></h2>

<p> </p>

<h3><em>IV/1. A felhasználó kötelességei és felelőssége</em></h3>

<p>A felhasználó köteles adatai megadása során kellő gondossággal eljárni. Az Üzemeltető nem tehető felelőssé azért a kárért, amely abból eredt, hogy a felhasználó adatai védelméről nem megfelelően gondoskodott.</p>

<p>A felhasználó az oldalt csak saját felelősségére használhatja. Az Üzemeltető nem vállal felelősséget a felhasználót az oldal használata során ért olyan károkért, kellemetlenségekért, amelyek abból adódtak, hogy a felhasználó az oldal használata során nem a kellő körültekintéssel járt el. A felhasználó adatait csak saját felelősségére hozhatja nyilvánosságra, teheti mások számára hozzáférhetővé.</p>

<p>A felhasználó köteles az oldal használata során tisztességesen, mások jogainak és érdekeinek szem előtt tartásával eljárni.</p>

<p>A felhasználó köteles tiszteletben tartani a hatályos jogszabályokat, és a használat során köteles tartózkodni minden olyan tevékenységtől, amely jogellenes, vagy amely mások érdekeit sérti. Ezen belül a felhasználó köteles tiszteletben tartani mások magánszféráját, személyhez fűződő jogait, a szellemi alkotásokhoz fűződő jogokat, különösen a szerzői jogi védelem alá eső irodalmi, tudományos és művészeti alkotások, találmányok, formatervezési minták, használati minták, védjegyek és forgalmi árujelzők védelmére vonatkozó szabályokat. A felhasználó köteles tartózkodni szabálysértés vagy bűncselekmény elkövetésétől, köteles tartózkodni továbbá minden olyan obszcén, trágár, illetve egyéb olyan kifejezéstől, megnyilatkozástól, amely alkalmas arra, hogy másokban megbotránkozást keltsen;</p>

<p>Valamennyi felhasználó köteles tartózkodni minden olyan tevékenységtől, amely az oldal rendeltetésszerű használatát akadályozza. Valamennyi felhasználó köteles tartózkodni minden olyan tevékenységtől, amely az Üzemeltető érdekeit sérti. Ezen belül a felhasználó köteles különösen:</p>

<p>-    Tartózkodni az oldal működésének megzavarásától, akadályozásától;</p>

<p>-    Tartózkodni olyan tevékenységektől, amely az Üzemeltető üzleti titkainak, általa titokban tartott információknak a megszerzésére, felhasználására irányul;</p>

<p>-    Tartózkodni minden olyan kommunikációtól, amely a szolgáltatásra vonatkozó, valótlan információt hordoz;</p>

<p>-    Tartózkodni minden olyan tevékenységtől, amely az oldal informatikai biztonságát veszélyezteti;</p>

<p>-    Az értékesítési tevékenységen túlmenően tartózkodni minden olyan tevékenységtől, amely saját, vagy más személy termékének vagy szolgáltatásának a reklámozására irányul.</p>

<p>A fentieken túl az Üzemeltető további korlátozásokat állapíthat meg, melyekről a felhasználókat tájékoztatja.</p>

<p>A felhasználó véleményéért maga vállalja a felelősséget, a felhasználók által közölt vélemények semmilyen esetben nem tekinthetők az Üzemeltető véleményének.</p>

<p>A felhasználó a Weboldalon közzétett információkat nem ruházhatja át ellenérték fejében, azokkal nem kereskedhet.</p>

<p>A felhasználók az oldal használata során más személyek adatait csak akkor hozhatják nyilvánosságra, tehetik mások számára hozzáférhetővé, ha ahhoz az érintett személy is hozzájárult. Az érintett hozzájárulása nem szükséges nyilvános közszereplése esetében, vagy az általa korábban korlátozás nélkül nyilvánosságra hozott adatok tekintetében.</p>

<p>A felhasználók a regisztráció során csak saját személyes adataikat adhatják meg. Más személyek adatainak megadása jogellenes adatkezelésnek minősül, amelynek a külön jogszabályokban meghatározott következményei lehetnek. Más személyes adataival való visszaélés esetén az Üzemeltető az eljáró hatóságoknak segítséget nyújt a jogsértés feltárása, a jogsértést elkövető azonosítása érdekében.</p>

<p>Jelen pontban írt korlátozások az oldal valamennyi látogatójára vonatkoznak.</p>

<p> </p>

<h3><em>IV/2. Az értékesítés szabályainak megszegése</em></h3>

<p>Amennyiben a felhasználó megszegi az értékesítés szabályait, az Üzemeltető jogosult az értékesítés felfüggesztésére. Ebben az esetben az Üzemeltető felszólítja a felhasználót a Szabályzatnak megfelelő működésre. Amennyiben ennek a felhasználó nem tesz eleget, az Üzemeltető jogosult a felhasználó regisztrációjának törlésére.</p>

<p> </p>

<h3><em>IV/3. Eljárás a szabálysértő felhasználókkal szemben</em></h3>

<p>Amennyiben a felhasználó a jelen Szabályzatban foglaltakat, vagy jogszabályban foglaltakat megszegi, az Üzemeltető a felhasználó regisztrációját törölheti. Ebben az esetben a felhasználó regisztrációja megszűnik, és a jövőben az oldal szolgáltatásait nem veheti igénybe.</p>

<p>Amennyiben a felhasználó magatartása alapján hatósági, bírósági eljárásnak van helye, az Üzemeltető a felhasználó azonosításához szükséges adatait, továbbá a jogsértésre vonatkozó adatokat a regisztráció törlésétől független tárolhatja, és az eljáró szerveknek átadhatja.</p>

<p>Amennyiben a felhasználó harmadik fél jogait sérti, és ezen harmadik fél eljárás kezdeményezésére jogosult, az Üzemeltető az adatokat a harmadik félnek átadhatja, amennyiben a harmadik fél az ehhez fűződő jogszerű érdekét bizonyítja.</p>

<p> </p>

<h3><em>IV/4. Szellemi alkotások védelme</em></h3>

<p>A Weboldalon közzétett valamennyi szellemi alkotás – ide értve különösen, de nem kizárólagosan a szerzői műveket, adatbázisokat, keresési megoldásokat, felhasznált programokat és kódokat, közzétett adatokat, védjegyeket, szabadalmi oltalom alá eső alkotásokat, grafikai megoldásokat, design-elemeket, információkat – jogosultja az Üzemeltető, a feltöltött termékek esetében az adott termék gyártója, forgalmazója. A szellemi alkotások kizárólag az irányadó jogszabályokban foglaltak szerint használhatók fel.</p>

<p>Az Üzemeltető szellemi alkotásokhoz fűződő jogainak megsértése esetén minden esetben megteszi a jogai érvényesítéséhez szükséges lépéseket.</p>

<p>A felhasználó semmilyen módon nem jogosult a szellemi alkotások másolására, többszörözésére, hasznosítására, értékesítésére, módosítására, átdolgozására, vagy nyilvánosságra hozatalára.</p>

<p> </p>

<h2><strong>V. Jogérvényesítés</strong></h2>

<p> </p>

<h3><em>V/1. Az Üzemeltetőhöz benyújtott kifogás</em></h3>

<p>A felhasználók panaszaikkal, kifogásaikkal fordulhatnak közvetlenül az Üzemeltetőhöz, aki minden tőle telhetőt megtesz az esetleges jogsértések megszüntetése és orvoslása érdekében. Az Üzemeltető a hozzá benyújtott panaszokat megvizsgálja, és álláspontjáról, megtett intézkedéseiről a felhasználót tájékoztatja.</p>

<p> </p>

<h3><em>V/2. A jogérvényesítés egyéb módjai</em></h3>

<p>A felhasználó az információs önrendelkezési jogról és az információszabadságról szóló 2011. évi CXII. törvény alapján jogait az alábbi módokon érvényesítheti:</p>

<p>-    Panaszával fordulhat közvetlenül az Üzemeltetőhöz, aki a panaszt az V/1. pont szerint kivizsgálja;</p>

<p>-    Tiltakozhat az adatok kezelése ellen, mely esetben az Üzemeltető 15 napon belül megvizsgálja a tiltakozást és döntést hoz;</p>

<p>-    Fordulhat a Nemzeti Adatvédelmi és Információszabadság Hatósághoz (<a href="http://www.naih.hu/">www.naih.hu</a>);</p>

<p>-    Bírósági úton érvényesítheti igényét.</p>

<p>A személyes adatok védelmének körén kívül eső panaszaival a felhasználó fordulhat a hatáskörrel és illetékességgel rendelkező hatósághoz, továbbá igénye érvényesítése érdekében keresetet terjeszthet elő a hatáskörrel és illetékességgel rendelkező bírósághoz.</p>

</div>