<div class="blogContent">
	<article class="postItem">
		<header>
			<h1>
				<a href="<?=$this->url('blog').'/'.$this->post->slug;?>"><?=$this->post->title;?></a>
			</h1>
		</header>
        <? if($this->user && $this->user->blogadmin){?>
        <a href="/index/blogedit?id=<?=$this->post->id;?>" class="editLink">Szerkesztés</a>
        <? } ?>
		<time><?=$this->post->date->format('Y.m.d');?></time>
        
		<div class="body">
			<?=$this->post->body;?>
		</div>
	</article>
    
    <div class="blogComments">
        <h2 class="commentHeader">Hozzászólások</h2>
        <?=$this->partial('common/comments.phtml', $this->getVars());?>
    </div>
    
    <div class="buttonBack"><a href="<?=$this->url('blog');?>"> Vissza a blog főoldalára </a></div>
    
    <br />
    <br />
    
    <div class="lists">
		<div class="listsInner">
			<div class="fresh list">
				<div class="productList">
					<ul class="products">

						<? foreach($this->random as $product){?>
							<?=$this->partial('market/product-partial.phtml', array_merge($this->getVars(), array('product'=>$product, 'back'=>false, 'fix'=>false, 'nameTag'=>'h4')));?>
						<? } ?>

					</ul>
				</div>
		</div>
	</div>
        
    <div class="buttonBack"><a href="<?=$this->url('piac');?>"> tovább a börzére </a></div>
    
    
</div>
