<div class="blogContent">
    <?php if($this->user && $this->user->blogadmin){?>
        <a href="/index/blogedit" class="editLink">Új poszt</a>
    <?php } ?>
	<?php foreach($this->posts as $post){?>
	<article class="postItem index">
		<header>
			<h2>
				<a href="<?=$this->url('blog').'/'.$post->slug;?>"><?=$post->title;?></a>
			</h2>
		</header>
		<time><?=$post->date->format('Y.m.d');?></time>
		<div class="body">
			<?=$post->teaser;?>
		</div>
        <a href="<?=$this->url('blog').'/'.$post->slug;?>" class="moreLink">tovább</a>
    </article>
	<?php } ?>

</div>
