<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Blog cikk fölött -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-3214257663864441"
     data-ad-slot="6016293104"
     data-ad-format="auto"></ins>
<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
</script>

<div class="blogContent">
	<article class="postItem">
		<header>
			<h1>
				<a href="<?=$this->url('blog').'/'.$this->post->slug;?>"><?=$this->post->title;?></a>
			</h1>
		</header>
        <? if($this->user && $this->user->blogadmin){?>
        <a href="/index/blogedit?id=<?=$this->post->id;?>" class="editLink">Szerkesztés</a>
        <? } ?>
		<time><?=$this->post->date->format('Y.m.d');?></time>
        
		<div class="body">
			<?=$this->post->body;?>
		</div>
	</article>
    
    <div class="blogComments">
        <h2 class="commentHeader">Hozzászólások</h2>
        <?=$this->partial('common/comments.phtml', $this->getVars());?>
    </div>
    
    <div class="relatedPosts">
        <ul>
        <? foreach($this->relatedPosts as $relatedPost){?>
            <li data-url="<?=$this->url('blog').'/'.$relatedPost->slug;?>">
                <div class="relatedInner">
                    <p class="postTitle"><?=$relatedPost->title;?></p>
                    <div class="teaser"><?=$relatedPost->teaser;?></div>
                </div>
            </li>
        <? } ?>
        </ul>
    </div>
    
    <div class="buttonBack"><a href="<?=$this->url('blog');?>"> további cikkek </a></div>
    
    <br />
    <br />
    
    <div class="lists">
		<div class="listsInner">
			<div class="fresh list lazyRandom" data-partialoptions='{"back":false,"fix":false,"nameTag":"h4"}'>
				<div class="productList">
					<ul class="products">

					</ul>
				</div>
		</div>
	</div>
        
    <div class="buttonBack"><a href="<?=$this->url('piac');?>"> tovább a börzére </a></div>
    
    
</div>
