<div class="stat cookie">

    <h1>A csakbaba.hu Cookie-kezelési szabályzata</h1>
    
    <h3>Cookie-k</h3>
    
    <p>A csakbaba.hu weboldal cookie-kat használ, szabályzatunk a cookie-k használatát, illetve azok kezelésének és törlésének módját írja le.</p>
    
    <h3>Mi a cookie?</h3>
    
    <p>A számítógép merevlemezéről egy weboldalra megküldött információkat nevezzük “cookie”-nak. Ezek nem számítógépes programok, csupán kis méretű információs fájlok, melyek lehetővé teszik, hogy egy weboldal a felhasználó böngészési szokásairól adatokat rögzítsen. Manapság a legtöbb weboldal használ cookie-kat, ezzel is jobbá tegyék az oldal használatának felhasználói élményét.  A cookie-k segítségével a weboldal perszonalizált szolgáltatásokat nyújthat (például megjegyzi a bejelentkezési adatokat, látogató számára érdekes tartalmakat). Az így rögzített adatok nem kapcsolhatók össze egyéb személyes adatokkal.</p>
    <p>A honlap látogatásakor a technikai működés miatt a következő, adatokat minden esetben elküldi a böngésződ. A további adatok szerepelhetnek a kiszolgálóstatisztikánkban: böngésző típusa és verziója, operációs rendszer, hivatkozó URL-cím (korábban látogatott webhely), a hozzáféréshez használt számítógép IP-címe, valamint a látogatás dátuma és időpontja.</p>
    <p>Kizárólag belső és statisztikai célokból rögzítjük ezeket az adatokat.</p>
    <p>Különböző típusú cookie-k léteznek:</p>
    <ul>
        <li>- időleges cookie-k (munkamenet cookie), melyek a böngésző bezárásakor törlődnek</li>
        <li>- állandó cookie-k, amelyeket a böngésző nem töröl, hanem törlésig vagy érvényességük lejártáig aktívak maradnak (ez attól függ, hogy a weboldal mennyi időt adott meg a cookie élettartamaként).</li>
    </ul>
    <p>Weboldalunk a következő két fajta cookie-t alkalmazza:</p>
    <ul>
        <li>Átmeneti (session) cookie: ezek ideiglenes cookie-k, amik a Te böngészésednek a végéig kerülnek tárolásra a cookie file-ban. Ezek a cookie-k létfontosságúak az oldalon működő funkciók vagy alkalmazások helyes működéséhez.</li>
        <li>Állandó (persistent) cookie: állandó cookie-t a felhasználói élmény javításának céljából használunk (pl. hogy minél könnyebben eligazodj az oldalon). Ezek a cookie-k hosszabb ideig tárolja a böngésző a cookie file-ban. Ennek hossza függ attól, hogy a böngésződben milyen beállítást alkalmazol. Az állandó cookie-k teszik lehetővé, az információ továbbítását a web szerverre, amikor a felhasználó felkeresi a weboldalt.</li>
    </ul>
    <p>A cookie-t törölheti afelhasználó saját számítógépéről, és le is tilthatja böngészőjében telepítésüket, alkalmazásukat, viszont a cookie-k letiltása, ez ronthatja a felhasználói élményt.</p>
    <p>A cookie-k kezelésére általában a böngészők Eszközök/Beállítások menüjében az Adatvédelem beállításai menüpont alatt, cookie megnevezéssel lehetséges.</p>
     
    <h3>Hogyan törölhetők a cookie-k?</h3>
    <p>A legtöbb böngésző automatikusan fogadja a cookie-kat.</p>
    <p>A cookie-kat a böngésződben kikapcsolhatod, de ha ezt teszed, sok olyan funkciót elveszíthetsz, amik az oldal megfelelő használatához szükségesek.</p>
    <p>További független információt a cookie-król a www.aboutcookies.org oldalon találhatsz.</p>
    <p>A mobiltelefonon található cookie-k törléséről a készüléked használati utasításából tájékozódhatsz.</p>
    
    
    <h3>A Cookie-k listája</h3>
    <p>A személyre szabott felhasználói élmény érdekében ez a csakbaba.hu cookie-kat használ.  Ahányszor belépsz az oldalra, cookie-kat küld a számítógépedre, és azokhoz hozzáfér. Az alábbi cooki-kat használja sz oldal:</p>
    <br /><br />
    <table width="100%">
        <thead>
            <tr>
                <th><strong>Kategória</strong></th>
                <th><strong>Cél</strong></th>
                <th><strong>Élettartam</strong></th>
                <th><strong>1. vagy 3-ik fél cookie</strong></th>
            </tr>
        </thead>
            <tr>
                <td>Feltétlenül szükséges cookie-k</td>
                <td>A bejelentkezési állapot kezelése</td>
                <td>Munkamenet cookie</td>
                <td>1. fél cookie</td>
            </tr>
            <tr>
                <td>Teljesítmény cookie-k</td>
                <td>A weboldal látogatottságának követése</td>
                <td>Munkamenet és állandó cookie-k</td>
                <td>3-ik fél cookie</td>
            </tr>
        <tbody>
        
        </tbody>
    </table>

    <br /><br />

    <p><strong>a) Feltétlenül szükséges cookie-k</strong> - a weboldal használatához szükségesek, lehetővé teszik a weboldal használatát, funkcióinak működését, például a weboldal biztonsági részeihez való hozzáférést.  Ezek szükségesek, például az eladáshoz/ vásárláshoz.</p>
    <p><strong>b) Teljesítmény cookie-k</strong> – Ezek a cookie-k információkat gyűjtenek a weboldal használatról, például, hogy melyek a leggyakrabban látogatott oldalak, vagy milyen hibaüzenetet kapsz a weboldalról.  Ezek a cookie-k sem gyűjtenek a látogatót azonosító információkat.  ezek, a cookie-k által gyűjtött információk névtelenek és általánosak.  Kizáróag a weboldal jobb működésének céljából használhatjuk.</p>
    <p><strong>c) Funkció cookie-k</strong> - Ezek a cookie-k lehetővé teszik a felhasználó választásainak rögzítését (például: avatar név) és bővített, személyre szabott funkciók használatát segítik elő.  Ezen cookie-k által begyűjtött információk anonimek is lehetnek és nem alkalmasak a más weboldalak látogatásának követésére.</p>
    <p><strong>d) Célzott vagy reklám cookie-k</strong> - Ezek a cookie-k a felhasználó és érdeklődési körének megfelelő reklámok megjelenítéséhez használhatók.  Meghatározható velük egy reklám megjelenítés alkalmának darabszáma, valamint mérhető vele egy reklámkampány hatékonysága. Megjegyzik egy weboldal látogatását és az információkat megosztják más szervezetekkel, például a reklám közzétevőjével.  Általában ezek a célzott vagy reklám cookie-k kapcsolódna azokhoz a funkciókhoz, amiket a weboldal üzemeltetője nyújt.</p>
    <p>Jelen Jogi Nyilatkozat és Adatvédelmi Nyilatkozat elfogadásával, valamint a weboldal látogatásával és használatával elfogadod a cookie-k használatát.  A cookie-k használatát elfogadhatod a webböngésződben megadott beállításokkal is.</p>

</div>