<div class="fbLikeBox">
    <h2>Közösségünk</h2>
    <div class="fb-like-box" data-href="http://www.facebook.com/csakbaba.hu" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="true"></div>
</div>


<div class="linksFooter">
    <h2>Hasznos oldalak</h2>
    <div class="linksFooterContent">
    <ul>
        <li><a href="/impresszum"> Impresszum </a> <BR /></li>
        <li><a href="/aszf"> ÁSZF, adatvédelem </a> <BR /></li>
        <li><a href="/rolunk"> Rólunk </a></li>
        <li><a href="/kapcsolat"> Írj nekünk </a></li>
    </ul>
    </div>






    <span id="infoUsername" style="display: none;"></span>

</div>

<div class="infoLogos">
    <img src="/img/elements/SSL_ClassB.png" alt="NetLock SSL - Hiteles oldal" title="NetLock SSL - Hiteles oldal"/>
</div>

<!--<div class="contactFooter">-->
<!--	<h2>Írj nekünk</h2>-->
<!--	--><?//=$this->contactForm;?>
<!--</div>-->


<div class="infos">
    <p class="copyright">© Minden jog fenntartva: Csakbaba.hu Kft., 2015</p>
</div>