<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Minden oldalon footer fölött -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-3214257663864441"
     data-ad-slot="6068745412"
     data-ad-format="auto"></ins>
<script>
	(adsbygoogle = window.adsbygoogle || []).push({});
</script>


<div class="fbLikeBox">
    <h2>Közösségünk</h2>
    <div class="fb-like-box" data-href="http://www.facebook.com/csakbaba.hu" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="true"></div>
</div>


<div class="linksFooter">
    <h2>Hasznos oldalak</h2>
    <div class="linksFooterContent">
    <ul>
        <li><a href="/impresszum"> Impresszum </a></li>
        <li><a href="/aszf"> ÁSZF, adatvédelem </a></li>
        <li><a href="/cookie-szabalyzat"> Cookie kezelési szabályzat </a></li>
        <li><a href="/rolunk"> Rólunk </a></li>
        <li><a href="/kapcsolat"> Írj nekünk </a></li>
    </ul>
    </div>






    <span id="infoUsername" style="display: none;"></span>

</div>

<div class="infoLogos">
    <img src="/img/elements/SSL_ClassB.png" alt="NetLock SSL - Hiteles oldal" title="NetLock SSL - Hiteles oldal"/>
    <img src="/img/elements/barion_footer.png" alt="Fizetés bankkártyával és Barionnal" title="Fizetés bankkártyával és Barionnal" class="barion"/>
</div>

<!--<div class="contactFooter">-->
<!--	<h2>Írj nekünk</h2>-->
<!--	--><?//=$this->contactForm;?>
<!--</div>-->


<div class="infos">
    <p class="copyright">© Minden jog fenntartva: Csakbaba.hu Kft., 2017</p>
</div>