

<div class="categorySelector">

</div>

<div class="search">
	<?=$this->searchForm;?>
</div>



<div class="usermenu">
	<? if($this->user){?>
		<a href="<?=$this->url('profil').'/'.urlencode($this->user->username);?>" class="account" title="Profil"><?=$this->user->username;?></a>
	  <a href="<?=$this->url('kijelentkezes');?>" class="logout" title="Kijelentkezés"><img src="/img/elements/logout.png" title="logout" alt="logout"></a>
	<? } else { ?>
		<div class="loginLink"><a href="javascript:void(0)" class="login">Bejelentkezés</a></div>
		<div class="loginreg">
			<div class="socialLogin">
				<a href="/slogin?s=fb&r=<?=urlencode(Zend_Controller_Front::getInstance()->getRequest()->getUri());?>" class="fb" title="Bejelentkezés Facebook fiókkal">Facebook</a>
				<a href="/slogin?s=gp&r=<?=urlencode(Zend_Controller_Front::getInstance()->getRequest()->getUri());?>" class="gp" title="Bejelentkezés Goggle fiókkal">Google</a>
			</div>
			<?=$this->loginform;?>
			<a href="<?=$this->url('elfelejtett');?>" class="forgotten">Elfelejtett jelszó</a>
			<a href="<?=$this->url('regisztracio');?>" class="registration">Regisztráció</a>
		</div>
	<? } ?>
</div>