<div class="sliderContainer">
	<div class="slider">
		<div><img src="/img/slider/s11.jpg" alt="csakbaba.hu" /></div>
		<div><img src="/img/slider/s12.jpg" alt="csakbaba.hu" /></div>
		<div><img src="/img/slider/s13.jpg" alt="csakbaba.hu" /></div>
		<div><img src="/img/slider/s14.jpg" alt="csakbaba.hu" /></div>
	</div>
	<div class="search">
		<?
			$searchFormClone=clone $this->searchForm;
			$searchFormClone->getElement('q')->setAttrib('id', 'qs');
			$searchFormClone->getElement('category_id')->setAttrib('id', 'category_idc');
			$searchFormClone->getElement('Keresés')->setAttrib('id', 'Keresésc');
		?>
		<?=$searchFormClone;?>
	</div>
</div>

<div class="mainContent">

	<div class="homeIcons">
        <div class="link"><a href="<?=$this->url('felhasznalotermekek');?>?uj" class="upload link">ingyenes <span class="bigger">termékfeltöltés</span></a></div>
        <div class="link"><a href="<?=$this->url('piac');?>" class="market link">tovább a <span class="bigger">börzére</span></a></div>
        <div class="link"><a href="<?=$this->url('regisztracio');?>" class="registration link">villámgyors<span class="bigger">regisztráció</span></a></div>
        <div class="clear"></div>
        <div class="borzeIcons">
            <? foreach($this->catMultiArray as $mainCat){?>
                <a href="<?=$this->url('piac').$mainCat->url;?>" class="<?=$mainCat->id;?>"><?=$mainCat->name;?></a>
            <? } ?>
        </div>
	</div>
    
    <div class="mora">
        <a href="http://www.mora.hu/affiliate_url.php?id=38" target="_blank"><img src="/img/elements/banner/csakbaba-affiliate-akcios-csomagok.jpg" alt="Akciós csomagok"/></a>
    </div>




	<div class="promoter">
		<? foreach($this->categoryTree->_multiArray as $key=>$mainCat){?>
			<? if(empty($this->promoteFirst[$key])) continue;?>
			<h2><a href="<?=$this->url('kiemelt').'/'.$key;?>"> Kiemelt termékek a <?=$mainCat->promoteName;?> kategóriában </a></h2>
			<?=$this->partial('index/promote_partial.phtml', array('products'=>$this->promoteFirst[$key], 'type'=>'first', 'categoryTree'=>$this->categoryTree, 'request'=>$this->request, 'nameTag'=>'h4'));?>
		<? } ?>

	</div>

	<div class="lists">
		<div class="listMenu">
			<div><a href="javascript:void(0)" data-list="0">Legfrissebb termékek</a></div>
			<div><a href="javascript:void(0)" data-list="1">Legnépszerűbb termékek</a></div>
			<span></span>
		</div>
		<div class="listsInner">
			<div class="fresh list">
				<div class="productList">
					<ul class="products">

						<? foreach($this->fresh as $product){?>
							<?=$this->partial('market/product-partial.phtml', array_merge($this->getVars(), array('product'=>$product, 'back'=>false, 'fix'=>false, 'nameTag'=>'h4')));?>
						<? } ?>

					</ul>
				</div>
			</div>

			<div class="visited list">
				<div class="productList">
					<ul class="products">

						<? foreach($this->visited as $product){?>
							<?=$this->partial('market/product-partial.phtml', array_merge($this->getVars(), array('product'=>$product, 'back'=>false, 'fix'=>false, 'nameTag'=>'h4')));?>
						<? } ?>

					</ul>
				</div>
			</div>

		</div>

	</div>


    <div class="homeToMarket"><a href="<?=$this->url('piac');?>" class="link">tovább a börzére</a></div>


	<div class="lists">
		<div class="listMenu">
			<? if($this->promotedUsers){?><div><a href="javascript:void(0)" data-list="0">Kiemelt asztalok</a></div><? } ?>
			<? if($this->latestUsers){?><div><a href="javascript:void(0)" data-list="1">Asztalok ahol éppen vásárlás történt</a></div><? } ?>
			<span></span>
		</div>
		<div class="listsInner">
			<? if($this->promotedUsers){?>
				<div class="promoter">
					<?=$this->partial('index/promote_user_partial.phtml', array('users'=>$this->promotedUsers, 'type'=>'allfirst', 'request'=>$this->request));?>
				</div>
			<? } ?>
			<? if($this->latestUsers){?>
				<div class="promoter">
					<?=$this->partial('index/promote_user_partial.phtml', array('users'=>$this->latestUsers, 'type'=>'latest', 'request'=>$this->request));?>
				</div>
			<? } ?>
		</div>
	</div>

</div>



