<div class="sliderContainer">
	<div class="slider">
		<div><img src="/img/slider/s11.jpg" alt="csakbaba.hu" /></div>
		<div><img src="/img/slider/s12.jpg" alt="csakbaba.hu" /></div>
		<div><img src="/img/slider/s13.jpg" alt="csakbaba.hu" /></div>
		<div><img src="/img/slider/s14.jpg" alt="csakbaba.hu" /></div>
	</div>
	<div class="search">
		<?php
			$searchFormClone=clone $this->searchForm;
			$searchFormClone->getElement('q')->setAttrib('id', 'qs');
			$searchFormClone->getElement('category_id')->setAttrib('id', 'category_idc');
			$searchFormClone->getElement('Keresés')->setAttrib('id', 'Keresésc');
		?>
		<?=$searchFormClone;?>
	</div>
</div>

<div class="mainContent">

	<div class="homeIcons">
        <div class="link"><a href="<?=$this->url('felhasznalotermekek');?>?uj" class="upload link">ingyenes <span class="bigger">termékfeltöltés</span></a></div>
        <div class="link"><a href="<?=$this->url('piac');?>" class="market link">tovább a <span class="bigger">börzére</span></a></div>
        <div class="link"><a href="<?=$this->url('regisztracio');?>" class="registration link">villámgyors<span class="bigger">regisztráció</span></a></div>
        <div class="clear"></div>
        <div class="borzeIcons">
            <?php foreach($this->catMultiArray as $mainCat){?>
                <a href="<?=$this->url('piac').$mainCat->url;?>" class="<?=$mainCat->id;?>"><?=$mainCat->name;?></a>
            <?php } ?>
        </div>
	</div>
    
    <!--<div class="mora">
        <a href="http://www.mora.hu/affiliate_url.php?id=38" target="_blank"><img src="/img/elements/banner/csakbaba-affiliate-akcios-csomagok.jpg" alt="Akciós csomagok"/></a>
    </div>-->




	<div class="promoter">
		<?php foreach($this->categoryTree->_multiArray as $key=>$mainCat){?>
			<?php if(empty($this->promoteFirst[$key])) continue;?>
			<h2><a href="<?=$this->url('kiemelt').'/'.$key;?>"> Kiemelt termékek a <?=$mainCat->promoteName;?> kategóriában </a></h2>
			<?=$this->partial('index/promote_partial.phtml', array('products'=>$this->promoteFirst[$key], 'type'=>'first', 'categoryTree'=>$this->categoryTree, 'request'=>$this->request, 'nameTag'=>'h4'));?>
		<?php } ?>

	</div>

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- Főoldal kiemelések alatt -->
    <ins class="adsbygoogle"
         style="display:block"
         data-ad-client="ca-pub-3214257663864441"
         data-ad-slot="1229024378"
         data-ad-format="auto"></ins>
    <script>
		(adsbygoogle = window.adsbygoogle || []).push({});
    </script>

    <br /><br />

	<div class="lists">
		<div class="listMenu">
			<div><a href="javascript:void(0)" data-list="0">Legfrissebb termékek</a></div>
			<div><a href="javascript:void(0)" data-list="1">Legnépszerűbb termékek</a></div>
			<span></span>
		</div>
		<div class="listsInner">
			<div class="fresh list">
				<div class="productList">
					<ul class="products">

						<?php foreach($this->fresh as $product){?>
							<?=$this->partial('market/product-partial.phtml', array_merge($this->getVars(), array('product'=>$product, 'back'=>false, 'fix'=>false, 'nameTag'=>'h4')));?>
						<?php } ?>

					</ul>
				</div>
			</div>

			<div class="visited list">
				<div class="productList">
					<ul class="products">

						<?php foreach($this->visited as $product){?>
							<?=$this->partial('market/product-partial.phtml', array_merge($this->getVars(), array('product'=>$product, 'back'=>false, 'fix'=>false, 'nameTag'=>'h4')));?>
						<?php } ?>

					</ul>
				</div>
			</div>

		</div>

	</div>


    <div class="homeToMarket"><a href="<?=$this->url('piac');?>" class="link">tovább a börzére</a></div>

    <br />
    <div class="purissimoBanner" style="text-align: center;">
        <a href="http://purissimo.hu/" target="_blank" style="display: block; max-width: 100%"><img src="/img/elements/banner/purissimo.gif" alt="Purissimo" style="max-width: 100%" /></a>
    </div>
    <br />


	<div class="lists">
		<div class="listMenu">
			<?php if($this->promotedUsers){?><div><a href="javascript:void(0)" data-list="0">Kiemelt asztalok</a></div><?php } ?>
			<?php if($this->latestUsers){?><div><a href="javascript:void(0)" data-list="1">Asztalok ahol éppen vásárlás történt</a></div><?php } ?>
			<span></span>
		</div>
		<div class="listsInner">
			<?php if($this->promotedUsers){?>
				<div class="promoter">
					<?=$this->partial('index/promote_user_partial.phtml', array('users'=>$this->promotedUsers, 'type'=>'allfirst', 'request'=>$this->request));?>
				</div>
			<?php } ?>
			<?php if($this->latestUsers){?>
				<div class="promoter">
					<?=$this->partial('index/promote_user_partial.phtml', array('users'=>$this->latestUsers, 'type'=>'latest', 'request'=>$this->request));?>
				</div>
			<?php } ?>
		</div>
	</div>

</div>



