<header class="sidebar <?=((!empty($_COOKIE['stick']) && $_COOKIE['stick']=='true')?'stick':'');?>">
    <div class="sidebarButtons"><div class="stick_it"><a href="javascript:void(0)"></a></div>
        <div class="hamburger_menu"><a href="javascript:void(0)"></a></div>
    </div>
    <a href="/" class="logo"><img property="og:image" src="/img/elements/logo.png " title="logo" alt="logo"/></a>
		<div class="borzeIcons">
			<? foreach($this->catMultiArray as $mainCat){?>
				<a href="<?=$this->url('piac').$mainCat->url;?>" class="<?=$mainCat->id;?>"><?=$mainCat->name;?></a>
			<? } ?>
		</div>
    <div class="menu">
        <nav><?=$this->navigation($this->nav)->menu()->setMaxDepth(1);?></nav>
    </div>

    <div class="bottom">
        <div class="colorChanger">
            <ul>
                <li data-col="brown" class="brown <?=($this->color=='brown') ? 'active' : '';?>"><a href="javascript:void(0);" title="Barna"></a></li>
                <li data-col="blue" class="blue <?=($this->color=='blue') ? 'active' : '';?>"><a href="javascript:void(0);" title="Kék"></a></li>
                <li data-col="pink" class="pink <?=($this->color=='pink') ? 'active' : '';?>"><a href="javascript:void(0);" title="Rózsaszín"></a></li>
            </ul>
        </div>

        <div class="socialmenu">
            <a href="https://www.facebook.com/csakbaba.hu" target="_blank" class="social fb"></a>
            <a href="https://plus.google.com/110411126847173107547" target="_blank" class="social gp"></a>
            <a href="http://www.pinterest.com/csakbaba/" target="_blank" class="social pr"></a>
            <a href="<?=$this->url('contact');?>" class="social email"></a>
        </div>

	      <p class="copyright">© 2017 Csakbaba.hu Kft.</p>
    </div>



</header>
