<?=$this->doctype();?>
<html lang="hu" class="<?=$this->htmlClass;?>">
<head>
	<?=$this->headMeta();?>
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<link rel="publisher" href="https://plus.google.com/110411126847173107547">
	<meta name="google-site-verification" content="RZKHjoN5ku2n-thZpzudSjI9Da41R9BKk6PT57l_Pz0" />
	<?=$this->headTitle();?>
	<?=$this->headStyle();?>
	<?=$this->minifyHeadLink();?>
	<?=$this->minifyHeadScript();?>
</head>
<body>
	<div id="container" class="ajax <?=$this->pageResourceSlug;?>">
		<?=$this->placeholder('content');?>
	</div>
</body>
</html>