<?=$this->doctype();?>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=Cantora+One|Capriola|McLaren&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
	<?=$this->headTitle();?>
	<?=$this->headMeta();?>
	<?=$this->headStyle();?>
	<?=$this->headLink();?>
	<?=$this->headScript();?>
</head>
<body>
	<div id="container" class="ajax <?=$this->pageResourceSlug;?>">
		<?=$this->placeholder('content');?>
	</div>
</body>
</html>