<?=$this->doctype();?>
<html class="<?=$this->htmlClass;?>">
<head>
	<script>document.cookie='resolution='+Math.max(screen.width,screen.height)+'; path=/';</script>
	<?=$this->headMeta();?>
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<link rel="publisher" href="https://plus.google.com/110411126847173107547">
	<?=$this->headTitle();?>
	<?=$this->headStyle();?>
	<?=$this->minifyHeadLink();?>
	<?=$this->minifyHeadScript();?>

	<script type="text/javascript">
		var _gaq = _gaq || [];
		_gaq.push(['_setAccount', 'UA-48324090-1']);
		_gaq.push(['_setCustomVar', 1, 'username', '<?=$this->user ? $this->user->username : 'notregistered';?>', 1]);
		_gaq.push(['_setCustomVar', 2, 'gender', '<?=$this->user ? $this->user->gender : 'notset';?>', 1]);
		_gaq.push(['_setCustomVar', 3, 'age', '<?=($this->user && is_object($this->user->birth_date)) ? $this->user->birth_date->diff(new DateTime())->y : 'notset';?>', 1]);
		_gaq.push(['_trackPageview']);
		(function() {
			var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
			ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
			var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
		})();
	</script>
	<!--[if lt IE 11]><link rel="stylesheet" href="/css/ie10.css"/><![endif]-->
	<!--[if lt IE 10]><script type="text/javascript" src="/js/jquery/jquery.placeholder.js"></script><![endif]-->
	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><link rel="stylesheet" href="/css/ie8.css"/><![endif]-->
</head>
<body>
<div id="fb-root"></div>
<script>
	$(window).load(function(){
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/hu_HU/all.js#xfbml=1&appId=267991083361773";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	});
</script>

<?=$this->messenger();?>
	<div id="container" class="<?=$this->pageResourceSlug;?>">
		<?=$this->placeholder('sidebar');?>
		<?=$this->placeholder('header');?>
		<?=$this->placeholder('subheader');?>
		<?=$this->placeholder('content');?>
		<?=$this->placeholder('footer');?>
	</div>
</body>
</html>