<?=$this->doctype();?>
<html lang="hu" class="<?=$this->htmlClass;?>">
<head>
	<script>document.cookie='resolution='+Math.max(screen.width,screen.height)+'; path=/';</script>
	<?=$this->headMeta();?>
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<link rel="apple-touch-icon" href="/apple-touch-icon.png">
	<link rel="publisher" href="https://plus.google.com/110411126847173107547">
	<meta name="google-site-verification" content="RZKHjoN5ku2n-thZpzudSjI9Da41R9BKk6PT57l_Pz0" />
	<link rel="schema.dcterms" href="http://purl.org/dc/terms/">
	<meta name="DC.coverage" content="Hungary" />
	<meta name="DC.description" content="csakbaba.hu - Használt baba és gyerek ruházat, online bababörze" />
	<meta name="DC.format" content="text/html" />
	<meta name="DC.identifier" content="https://csakbaba.com" />
	<meta name="DC.publisher" content="Csakbaba.hu" />
	<meta name="DC.title" content="csakbaba.hu - Használt baba és gyerek ruházat, online bababörze" />
	<meta name="DC.type" content="Text" />
	<?=$this->headTitle();?>
	<?=$this->headStyle();?>
	<?=$this->minifyHeadLink();?>
	<?=$this->minifyHeadScript();?>

	<script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
		ga('create', '<?=ANALYTICS_ID;?>', 'auto');
		ga('set', 'dimension1', '<?=$this->user ? $this->user->username : 'notregistered';?>');
		ga('set', 'dimension2', '<?=$this->user ? $this->user->gender : 'notset';?>');
		ga('set', 'dimension3', '<?=($this->user && is_object($this->user->birth_date)) ? $this->user->birth_date->diff(new DateTime())->y : 'notset';?>');
		//ga('require', 'displayfeatures');
		ga('send', 'pageview');

	</script>

	<!--[if lt IE 11]><link rel="stylesheet" href="/css/ie10.css"/><![endif]-->
	<!--[if lt IE 10]><script type="text/javascript" src="/js/jquery/jquery.placeholder.js"></script><![endif]-->
	<!--[if lt IE 9]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><link rel="stylesheet" href="/css/ie8.css"/><![endif]-->
</head>
<body>
<div id="fb-root"></div>
<script>
	$(window).load(function(){
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) return;
			js = d.createElement(s); js.id = id;
			js.src = "//connect.facebook.net/hu_HU/all.js#xfbml=1&appId=267991083361773";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	});
</script>

<?=$this->messenger();?>
	<div id="container" class="<?=$this->pageResourceSlug;?>">
		<?=$this->placeholder('sidebar');?>
		<?=$this->placeholder('header');?>
		<?=$this->placeholder('subheader');?>
		<?=$this->placeholder('content');?>
		<?=$this->placeholder('footer');?>
	</div>
</body>
</html>